### ISSUE TITLE
implement kml output / sitemap

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#10]
Initial idea: http://www.lockedowndesign.com/local-seo-geo-sitemap-generator/

Comment by dvh:
Google appearantly dropped support for Geo Sitemaps. Instead you can support a link to a KML file in your normal sitemap. See also:
- https://plus.google.com/+SusanMoskwa/posts/CmZejMkLN4r
- http://www.sitemapdoc.com/Geositemap-Generator.aspx

**Comment by cportele** [comment]
no longer relevant - issue can be closed

**Comment by akuckartz** [comment]
Why is that "no longer relevant" ?

**Comment by cportele** [comment]
As far as I know the conclusion is that there is no Google SEO benefit from using "KML sitemaps" (which is what this issue was about).
