### ISSUE TITLE
Snapshot tag still present despite using building release

### ISSUE THREAD

**Issue by ghelle-fhh** [interactive-instruments/ldproxy#1006]
### ldproxy Version

v3.4.1

### Current Behavior

Hallo,

I've checked out the tag v3.4.1 from github and build the distribution with the gradle commands as described in the documentation

However the logs print out:

"Starting ldproxy v3.4.1-SNAPSHOT"

I see gradle takes a variable versionSuffix: https://github.com/interactive-instruments/ldproxy/blob/v3.4.1/version.gradle

Have I taken the correct release and this is just a small bug, or have I done something wrong?

### Expected Behavior

Starting ldproxy v3.4.1-RELEASE or Starting ldproxy v3.4.1

### Steps to Reproduce

1. Checkout branch tag v3.4.1
2. Build distribution with ./gradlew distZip
3. Run ldproxy/bin/ldproxy
4. View xtraplafrom log

### Relevant log output

```shell
INFO  [2023-07-06 08:52:04,131]                          - --------------------------------------------------  
INFO  [2023-07-06 08:52:04,133]                          - Starting ldproxy v3.4.1-SNAPSHOT
```

**Comment by azahnen** [comment]
This is neither a bug nor something we officially support. That being said, if you want to create a release build yourself, it should work like this:

```sh
./gradlew distZip -Prelease=true
```
