### ISSUE TITLE
Apache Reverseproxy for ldproxy

### ISSUE THREAD

**Issue by mattenp** [interactive-instruments/ldproxy#1052]
### ldproxy Version

3.4.2

### Current Behavior

Hi,

I would like to use Apache Web Server as reverse proxy for ldproxy, but it does not really works.

Best regards,

Matthias

Federal Maritime and Hydrographic Agency Hamburg

### Expected Behavior

Using https://hostname/ldproxy instead of http://hostname:7080

### Steps to Reproduce

Apache config in VirtualHost:443:
```
ProxyPass /ldproxy http://localhost:7080
ProxyPassReverse /ldproxy http://localhost:7080
```

ldproxy as extracted distTar
data/cfg.yml
```
server:
  externalUrl: https://hostname/ldproxy
```

**Comment by cportele** [comment]
See #1051. This is not an ldproxy bug, so I am closing this issue.
