### ISSUE TITLE
DEBUG log messages despite logging.level set to INFO

### ISSUE THREAD

**Issue by schmity** [interactive-instruments/ldproxy#1075]
### ldproxy Version

3.5.0.

### Current Behavior

In cfg.yml logging.level is set to INFO. However, in xtraplatform.log DEBUG messages are logged. 
Find cfg.yml attached and an excerpt from xtraplatform.log below.

[cfg.txt](https://github.com/interactive-instruments/ldproxy/files/12871259/cfg.txt)

### Expected Behavior

Log-entries to xtraplatform.log respect logging.level.

### Steps to Reproduce

- start ldproxy with cfg.yml
- navigate through an API 
- check logs for DEBUG messages

### Relevant log output

```shell
INFO  [2023-10-11 16:37:32,634] zulaessige_hoechstgeschw - Service with id 'zulaessige_hoechstgeschwindigkeiten' started successfully.  
DEBUG [2023-10-11 16:42:10,995]                          - Processing request: GET /rest/services [a912e9cf-f3c0-40c0-8988-c66f2fd281d4] 
DEBUG [2023-10-11 16:42:11,052]                          - Sending response: 200 OK [a912e9cf-f3c0-40c0-8988-c66f2fd281d4] 
DEBUG [2023-10-11 16:42:14,334] stadtgruen               - Processing request: GET / [c5e23f1a-a28e-4757-b09c-aa4c7ce18670] 
DEBUG [2023-10-11 16:42:14,373] stadtgruen               - Sending response: 200 OK [c5e23f1a-a28e-4757-b09c-aa4c7ce18670] 
DEBUG [2023-10-11 16:42:17,433] stadtgruen               - Processing request: GET /collections [9439c082-eeea-4daa-9491-84bbc4d42116] 
DEBUG [2023-10-11 16:42:17,475] stadtgruen               - Sending response: 200 OK [9439c082-eeea-4daa-9491-84bbc4d42116]
```

**Comment by azahnen** [comment]
Could you post a full log of the startup with `logging.level: DEBUG`?

**Comment by azahnen** [comment]
I am mainly interested in the first 20 lines or so, startup of all the providers and APIs is not needed.

**Comment by cportele** [comment]
@azahnen 

I have observed the same behavior. `LOGGER.isDebugEnabled(MARKER.REQUEST)` is `true`, `LOGGER.isDebugEnabled()` is `false`. 

The reason seems to be that `LOGGER.isDebugEnabled(MARKER.REQUEST)` calls the `LoggingFilter.decide()` function with `Level.DEBUG` which in turn always returns `ACCEPT`, because of:

```java
    if (Objects.equals(marker, MARKER.REQUEST)
        && (apiRequests || level == Level.DEBUG || level == Level.TRACE)) {
      return FilterReply.ACCEPT;
    }
```

I can also copy the startup log here, but I did not see anything that was related to this behavior.

**Comment by schmity** [comment]
Hi, 
full log of the startup with logging.level: DEBUG (with an empty store):

INFO  [2023-10-13 08:14:45,902]                          - --------------------------------------------------  
INFO  [2023-10-13 08:14:45,902]                          - Starting ldproxy v3.5.0  
DEBUG [2023-10-13 08:14:46,457]                          - Data directory: /ldproxy/data  
DEBUG [2023-10-13 08:14:46,457]                          - Environment: CONTAINER  
DEBUG [2023-10-13 08:14:46,459]                          - Base configurations: [cfg.base.yml, cfg.console.yml]  
DEBUG [2023-10-13 08:14:46,459]                          - User configurations: [FS[cfg.yml]]  
INFO  [2023-10-13 08:14:48,632]                          - Loading store (writable)  
INFO  [2023-10-13 08:14:48,633]                          -   FS cfg.yml [CFG] [RO]  
INFO  [2023-10-13 08:14:48,633]                          -   FS store [ENTITIES] [RW]  
INFO  [2023-10-13 08:14:48,633]                          -   FS api-resources [RESOURCES] [RW]  
INFO  [2023-10-13 08:14:48,633]                          -   FS api-resources/resources [RESOURCES] [api-resources] [RW]  
INFO  [2023-10-13 08:14:48,633]                          -   FS store/resources [RESOURCES] [RO]  
INFO  [2023-10-13 08:14:48,633]                          -   FS cache/tiles [RESOURCES] [tiles] [RW]  
INFO  [2023-10-13 08:14:48,633]                          -   FS cache/tiles3d [RESOURCES] [tiles3d] [RW]  
INFO  [2023-10-13 08:14:48,633]                          -   FS proj [RESOURCES] [proj] [RW]  
INFO  [2023-10-13 08:14:48,634]                          -   FS templates/html [RESOURCES] [html/templates] [RO]  
DEBUG [2023-10-13 08:14:48,659]                          - Resources of type html/templates for FS[templates/html] ready  
DEBUG [2023-10-13 08:14:48,660]                          - Resources of type proj for FS[proj] ready and writable  
DEBUG [2023-10-13 08:14:48,660]                          - Resources of type tiles3d for FS[cache/tiles3d] ready and writable  
DEBUG [2023-10-13 08:14:48,660]                          - Resources of type tiles for FS[cache/tiles] ready and writable  
DEBUG [2023-10-13 08:14:48,660]                          - Resources for FS[store/resources] ready  
DEBUG [2023-10-13 08:14:48,660]                          - Resources of type api-resources for FS[api-resources/resources] ready and writable  
DEBUG [2023-10-13 08:14:48,661]                          - Resources for FS[api-resources] ready and writable  
DEBUG [2023-10-13 08:14:48,671]                          - Loading defaults  
DEBUG [2023-10-13 08:14:48,673]                          - Loaded defaults  
DEBUG [2023-10-13 08:14:48,673]                          - Loading entities  
DEBUG [2023-10-13 08:14:48,673]                          - Loading overrides  
DEBUG [2023-10-13 08:14:48,676]                          - Loaded entities and overrides  
DEBUG [2023-10-13 08:14:48,795]                          - PROJ version: Rel. 9.1.0, September 1st, 2022, location: /ldproxy/data/./proj  
INFO  [2023-10-13 08:14:49,401]                          - Started web server at http://localhost:7080  
DEBUG [2023-10-13 08:16:05,324]                          - Processing request: GET /rest/services [d6f9c879-333c-4ce2-8635-0e6aadb771bf] 
DEBUG [2023-10-13 08:16:05,714]                          - Sending response: 200 OK [d6f9c879-333c-4ce2-8635-0e6aadb771bf]

**Comment by azahnen** [comment]
Thanks, that does not reveal any obvious issues. Then I am pretty sure that @cportele is right and this is a bug in the `LoggingFilter`. I will provide a fix.
