### ISSUE TITLE
time parameter and temporal extent

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#108]
1. time
Along the lines of the bbox parameter, this will test against the first date-like property that is found in the mapping for the feature type.
In the future the manager should allow to set the main temporal property.

2. temporal extent
This cannot be derived from the Capabilities like the spatial extent, so it would have to be computed. That is too slow on-the-fly, so the value would have to be cached.
As this is optional, it will not be implemented yet.

**Comment by cportele** [comment]
Regarding item 2: The extent could be configured in the manager.

Supporting the configuration of both items in the manager should be included.
