### ISSUE TITLE
Datetime queries fails

### ISSUE THREAD

**Issue by guleri** [interactive-instruments/ldproxy#1099]
### ldproxy Version

3.4.3 and 3.5.0

### Current Behavior

When I do a datetime query like "datetime=2007-01-27T18:11:52Z/2018-11-22T09:42:12Z" using Ldproxy version 3.4.3 or 3.5.0, I get a "504 Gateway Time-out" error. When I do the exact same query, and the same ldproxy configuration and database connection, but with Ldproxy 3.3.4, the query runs fine.

### Expected Behavior

A result containing items with "oppdateringsdato" in the specified date range.

Example with version 3.3.4 that works: https://api.ra.no/rest/services/LokaliteterEnkeltminnerOgSikringssoner/collections/enkeltminner/items?datetime=2007-01-27T18%3A11%3A52Z%2F2018-11-22T09%3A42%3A12Z

### Steps to Reproduce

Using Ldproxy v. 3.4.3 or 3.50 (and I guess, the versions between), and a setup similar to mine. Its :

My database setup is Postgresql 13.11, PostGIS 3.3.2

Materialized view with 464525 rows unique btree index on the Id column and a btree index with sort order ascending on the date column.

My ldproxy settings:
```
Provider date property:
      oppdateringsdato:
        sourcePath: oppdateringsdato
        type: DATETIME
        role: PRIMARY_INSTANT
```

In my service config:
```
        temporal:
        - oppdateringsdato
```

### Relevant log output

```shell
Not a log output, but I've noticed that some of the Postgresql queries that are executed are different depending on the Ldproxy version.

When I use 3.3.4, this query is executed:

WITH
    NR AS (SELECT MIN(SKEY) AS minKey, MAX(SKEY) AS maxKey, count(*) AS numberReturned FROM (SELECT A.lokalid AS SKEY FROM api.kulturminner_geonorge A WHERE (A.lokalid IN (SELECT AA.lokalid FROM api.kulturminner_geonorge AA WHERE AA.minnetype IN ('ENK','LOKENK')) AND A.lokalid IN (SELECT AA.lokalid FROM api.kulturminner_geonorge AA WHERE (AA.oppdateringsdato::timestamp(0),AA.oppdateringsdato::timestamp(0)) OVERLAPS (TIMESTAMP '2008-01-27T18:11:52Z',TIMESTAMP '2019-11-22T09:42:12Z'))) ORDER BY SKEY LIMIT 10) AS IDS),
    NM AS (SELECT count(*) AS numberMatched FROM (SELECT A.lokalid AS SKEY FROM api.kulturminner_geonorge A WHERE (A.lokalid IN (SELECT AA.lokalid FROM api.kulturminner_geonorge AA WHERE AA.minnetype IN ('ENK','LOKENK')) AND A.lokalid IN (SELECT AA.lokalid FROM api.kulturminner_geonorge AA WHERE (AA.oppdateringsdato::timestamp(0),AA.oppdateringsdato::timestamp(0)) OVERLAPS (TIMESTAMP '2008-01-27T18:11:52Z',TIMESTAMP '2019-11-22T09:42:12Z'))) ORDER BY 1) AS IDS),
    NS AS (SELECT -1::bigint AS numberSkipped)
  SELECT * FROM NR, NM, NS


  But when I use 3.5.0, it is executed as follows:
 
WITH
    NR AS (SELECT MIN(SKEY) AS minKey, MAX(SKEY) AS maxKey, count(*) AS numberReturned FROM (SELECT A.lokalid AS SKEY FROM api.kulturminner_geonorge A WHERE (A.lokalid IN (SELECT AA.lokalid FROM api.kulturminner_geonorge AA WHERE AA.minnetype IN ('ENK','LOKENK')) AND (A.lokalid IN (SELECT AA.lokalid FROM api.kulturminner_geonorge AA WHERE (AA.oppdateringsdato::timestamp(0),AA.oppdateringsdato::timestamp(0)) OVERLAPS (TIMESTAMP '2007-01-27T18:11:52Z',TIMESTAMP '2018-11-22T09:42:12Z')) OR A.lokalid IN (SELECT AA.lokalid FROM api.kulturminner_geonorge AA WHERE AA.oppdateringsdato::timestamp(0) IS NULL))) ORDER BY SKEY LIMIT 10) AS IDS),
    NM AS (SELECT count(*) AS numberMatched FROM (SELECT A.lokalid AS SKEY FROM api.kulturminner_geonorge A WHERE (A.lokalid IN (SELECT AA.lokalid FROM api.kulturminner_geonorge AA WHERE AA.minnetype IN ('ENK','LOKENK')) AND (A.lokalid IN (SELECT AA.lokalid FROM api.kulturminner_geonorge AA WHERE (AA.oppdateringsdato::timestamp(0),AA.oppdateringsdato::timestamp(0)) OVERLAPS (TIMESTAMP '2007-01-27T18:11:52Z',TIMESTAMP '2018-11-22T09:42:12Z')) OR A.lokalid IN (SELECT AA.lokalid FROM api.kulturminner_geonorge AA WHERE AA.oppdateringsdato::timestamp(0) IS NULL))) ORDER BY 1) AS IDS),
    NS AS (SELECT -1::bigint AS numberSkipped)
  SELECT * FROM NR, NM, NS


  It's the NM part of the query that runs forever. The difference between this and the one ran using 3.3.4 is the last part:
  "OR A.lokalid IN (SELECT AA.lokalid FROM api.kulturminner_geonorge AA WHERE AA.oppdateringsdato::timestamp(0) IS NULL)"

  If I leave that part out, it runs fine. By the way, the result of that part alone is zero rows.
```

**Comment by cportele** [comment]
@guleri - Some quick observations:

1. It is not a general issue and may depend on your specific database setup, a query with that "datetime" value works fine in the ['CShapes' demo API](https://demo.ldproxy.net/cshapes/collections/boundary/items?datetime=2007-01-27T18:11:52Z/2018-11-22T09:42:12Z).
2. The query looks correct to me, but I just had a quick look.
3. The additional predicate was added because of [Requirement 26C](https://docs.ogc.org/is/17-069r4/17-069r4.html#req_core_fc-time-response), that is to return all features where the property has no value (is `null`).

**Comment by guleri** [comment]
One difference between the 'CShapes' demo API and my dataset, is the number of features. I also have other datasets with fewer features, where the datetime query works fine.

I'm not good at reading PostgreSQL query reports, but there is a quite a difference between how the query is handled with and without the additional "is null" predicate.

**With the "is null" predicate:**
[isNull.json](https://github.com/interactive-instruments/ldproxy/files/13459955/isNull.json)

**Without the "is null" predicate:**
[withoutIsNull.json](https://github.com/interactive-instruments/ldproxy/files/13459956/withoutIsNull.json)

I also tried to run the same query against a regular table instead of a materialized view, with the same bad performance. 

I'm not sure if it's the indexing that should be set up differently, or if it's something with the query or something else. Have you tested the query against a table with 250000+ rows? I have another dataset with 120925 rows, and it works fine.

**Comment by cportele** [comment]
The comparison of the query plans is helpful. 

I have just tested a `datetime` request with a collection with 10 million features. I don't get timeouts in v3.5, but the response time in v3.5 is multiple times the response time with v3.3. This is not a bug, but the behavior could (and should) be improved.

A workaround in a client would be to use for now a filter instead of the `datetime` parameter, that is `filter=t_intersects(oppdateringsdato,interval('2007-01-27T18:11:52Z','2018-11-22T09:42:12Z'))`.

**Comment by cportele** [comment]
One final thought for now. The `IS NULL` probably results in a full table scan. If that column is never `NULL`, you could specify the column as `NOT NULL`. Then the query planner should be able to discard the `property IS NULL` part of the query as it can never be true.

**Comment by guleri** [comment]
Thanks for checking and the suggestion.

Since I'm using materialized views, I'm not sure how to implement "not null" on the column. But I've tried on the table I mentioned above, and the query plan the query plan doesn't change at all. The query used 25 min. to finish.

I'm wondering if my table and index setup is much different from your 10 million table?

For the testing table, the modified column I'm using for the datetime query is set to "not null", the id column I'm using is the primary key, and other than that the indexes are as previously described.

My table definition:
[createTable.txt](https://github.com/interactive-instruments/ldproxy/files/13476562/createTable.txt)

**Comment by guleri** [comment]
I upgraded to version v3.6.2, and the SQL query turns out exactly the same as before, and times out. But maybe I'm missing the point of the changes done in #1158

**Comment by azahnen** [comment]
@guleri It seems the actual changes are described neither here nor in the PR, but a paragraph was added to the docs (https://docs.ldproxy.net/services/building-blocks/features.html#scope):

> If the primary instant is never `NULL`, the constraint `required: true` should be set for the property in the provider schema. This speeds up queries with the `datetime` parameter, especially with larger data sets.

So I wouldn't expect a different SQL query with the same configuration. What the changes provide is a way to set the `NOT NULL` constraint in the provider schema if it is inconvenient to do so in the SQL schema.

**Comment by guleri** [comment]
Like this in the provider? The SQL still turns out the same.

      oppdateringsdato:
        sourcePath: oppdateringsdato
        type: DATETIME
        role: PRIMARY_INSTANT        
        required: true

**Comment by azahnen** [comment]
No, it has to be in a `constraints` object, see https://docs.ldproxy.net/providers/details/constraints.html.
