### ISSUE TITLE
Bad Location redirect header with bbox filter and paging

### ISSUE THREAD

**Issue by rouault** [interactive-instruments/ldproxy#110]
"https://www.ldproxy.nrw.de/rest/services/kataster/collections/flurstueck/items?bbox=8.7,51.4,8.8,51.5&f=json&page=1&limit=10" with "Accept: application/geo+json, application/json" returns a
"http://www.ldproxy.nrw.de/rest/services/kataster/collections/flurstueck/items?bbox=8.7%2C51.4%2C8.8%2C51.5&f=json&page=2&limit=10" next link.
Note the http:// prefix, and not https://

When downloading this URL, the Location header value is
"""Location: https://www.ldproxy.nrw.de/rest/services/kataster/collections/flurstueck/items?bbox=8.7%252C51.4%252C8.8%252C51.5&f=json&page=2&limit=10"""
Note that the '%' character has been escaped to %25, whereas it shouldn't have, so when following this link, the server returns an empty response

**Comment by cportele** [comment]
Thanks for reporting these issues, @rouault !

**Comment by cportele** [comment]
the issue has been fixed (some time ago)
