### ISSUE TITLE
Add services from catalogue fails to add identified WFS

### ISSUE THREAD

**Issue by schmity** [interactive-instruments/ldproxy#120]
Hi, 
I run the iide/ldproxy:latest-container on a test-machine at http://51.5.151.78/, (downloaded today).

The Add services from catalogue would be great to use for our purpose (add all WFS services from Hamburg), but after detecting 213 WFS services from https://meatver.de/csw to add, it fails for all of them. http://51.5.151.78/rest/admin/services/ returns HTTP 500 for each service.

What I found is: 
the request payload POSTed to http://51.5.151.78/rest/admin/services/ when trying to add WFS from CSW is different to the one that is sent when manually adding a service. Manually adding works fine.

Best,
Sebastian

**Comment by azahnen** [comment]
Hi Sebastian,
this looks like a bug in the latest version, we will check that.
In the meantime you could try iide/ldproxy:v1.2.6, this issue as well as #121 shouldn't occur in that version.

**Comment by schmity** [comment]
Hi Andreas, 
thanks for the quick reply, both this issue and #121 work fine in 1.2.6
Best,
Sebastian

**Comment by azahnen** [comment]
Hi Sebastian,
you might try again with iide/ldproxy:t14. That's basically 1.3.0 with fixes for this and #121.
I am still testing for further regression bugs, after that I will release 1.3.1.

**Comment by schmity** [comment]
Hi Andreas, 
thanks for fixing this, adding WFS from CSW works fine in t14.

Best, 
Sebastian

**Comment by cportele** [comment]
The original issue is fixed, the admin manager (additional issue mentioned in the last comment) is going to be rewritten.
