### ISSUE TITLE
WFS default version should be 2.0.0

### ISSUE THREAD

**Issue by schmity** [interactive-instruments/ldproxy#121]
Hi,
I run the iide/ldproxy:latest-container on a test-machine at http://51.5.151.78/, (downloaded today).

Our WFS GetCapabilities document return two ServiceTypeVersion elements, one for 1.1.0 and one for 2.0.0 for any GetCapabilities request, even when the VERSION is specified in the request, e.g. https://geodienste.hamburg.de/HH_WFS_Schulen?Service=WFS&Version=2.0.0&Request=GetCapabilities 
When adding a service, 1.1.0 is added to the ldproxy config-store/entities/services/<service> file as featureProvider.version. With that set, the WFS is not working in ldproxy. Once I change it to 2.0.0 in the config-file and restart the container, it works fine.

Could ldproxy generally prefer 2.0.0 over 1.1.0 or even reject other versions than 2.0.0 altogether?

Best,
Sebastian

**Comment by akuckartz** [comment]
Isn't the most recent version 2.0.2 ?

**Comment by cportele** [comment]
Fixed by changes for #120
