### ISSUE TITLE
document maximumPageSize in OpenAPI document

### ISSUE THREAD

**Issue by schmity** [interactive-instruments/ldproxy#1219]
### Describe the Feature Request

The maximumPageSize for /items should be documented in the description of the limit-parameter in the OpenAPI document.

### Describe the Use Case

Developers should be made aware of the configured maximumPageSize as there is no error message, when the query parameter limit exceeds it, see https://github.com/interactive-instruments/ldproxy/issues/396

### Describe Preferred Solution

The maximumPageSize for /items should be documented in the description of the limit-parameter in the OpenAPI document.

**Comment by cportele** [comment]
The information is already part of the OpenAPI definition, Swagger UI just does not show this information by default.

Having an option to set [`showCommonExtensions`](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/) to `true` would also display `minimum`, `maximum` and other schema constraints for each parameter (not just `limit`). 

This is how it would look like:

<img width="1395" alt="Bildschirmfoto 2024-05-08 um 10 42 36" src="https://github.com/interactive-instruments/ldproxy/assets/4245251/1c3c5620-1b21-4a91-8cf1-3416e52b64c8">

@schmity - Would that work?

**Comment by cportele** [comment]
In addition, we should update the description of `limit` to point out that if the limit value is higher than the maximum no error is thrown, but the value is reduced to the maximum value.

**Comment by schmity** [comment]
Yes, that would work!

**Comment by schmity** [comment]
We observed some confusion about the maximumPageSize at a recent hackathon with IT-students, so it might be worth to additionally extend the introductory text for the /items resource like so: 
"To support access to larger collections without overloading the client, the API supports paged access with links to the next page, if more features are selected than the page size (maximum page size is <maximumPageSize>)."
