### ISSUE TITLE
OpenAPI links redirect to manager/#/services in v1.2.6 

### ISSUE THREAD

**Issue by schmity** [interactive-instruments/ldproxy#122]
Hi, 
following the quick advice on #120 and #121, I now run v1.2.6.
Adding services manually and from catalogue works fine. However, I find that the links to the OpenAPI docs do not resolve and redirect to /manager/#/services. 
For instance: http://51.5.151.78/rest/services/metaver_de_csw_204/api?f=html 

Any hints most welcome!

Best,
Sebastian

**Comment by cportele** [comment]
I think there was a problem in older versions that required trailing slashes, but including them still results in errors. Does this issue also occur in your environment with services that are created "manually" and not by the catalog harvester?

**Comment by schmity** [comment]
Hi, 
redirect happens in v1.2.6 for both manually and catalog harvested ones.
Adding a trailing slash to the api link works fine with manually added service (http://51.5.151.78/rest/services/manually1/api/?f=html), and results in "failed to load spec" for catalog harvested ones (http://51.5.151.78/rest/services/metaver_de_csw_195/api/?f=html). 

Mmh, while going back further in version history is one option, can you already tell whether and when you might be able to provide a fix for v1.3.0? 

By the way, we are planning to bring in WFS 3.0 for all Hamburg WFS into a Hackathon at October 19th, https://dbmindbox.com/de/db-opendata-hackathons/hackathons/mobility-meets-logistics-2-its-hackathon-hamburg-1920102018/  

Best, 
Sebastian

**Comment by cportele** [comment]
I don't think that going back further in time / versions would help, so it would require either a fix in 1.2 (ie 1.2.7) or in 1.3. We are currently very busy (or on vacation 😉), so it is hard to say when we can provide a fix. We should be able to have a closer look in the first week of October and see, if we can come up with a fix. Would that be ok?

**Comment by schmity** [comment]
That sounds good. We can continue evaluating ldproxy and WFS 3.0 with v1.3.0 till then with manually added services.

**Comment by schmity** [comment]
continue to work with t14 / 1.3.0, closing this issue.
