### ISSUE TITLE
simple security approach for rest interface / manager

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#13]
Explore if we can use HTTP Basic Auth or HTTP Token Auth as a simpler alternative to OAuth2. Alternatively, we could use our OAuth2 implementation limited to a single user.

http://techblog.thescore.com/2014/06/25/http-basic-authentication-and-http-token-authentication/
http://jwt.io/introduction/

**Comment by cportele** [comment]
Workaround:

use a staging/development development with Manager UI for configuration and testing and a production deployment without the Manager UI.

**Comment by cportele** [comment]
implemented, will be available in 2.0
