### ISSUE TITLE
Vector Tiles (vt) branch : enable tiles setting not saved?

### ISSUE THREAD

**Issue by schmity** [interactive-instruments/ldproxy#139]
Hi, 
I want to test the Vector Tiles extension for wfs3. I run iide/ldproxy:vt docker image at http://51.5.151.78:7080/. 
In the Tiles section of the configuration of one of the feature types in the manager at http://51.5.151.78:7080/manager/#/services/123/123_strassenbaumkataster checking ""Tiles enabled" will not be saved. and no tiles ressources are available in the OpenAPI page.

Is there something I am missing or is there a way to configure that through the config files?

Best, 
Sebastian

**Comment by azahnen** [comment]
Hi Sebastian,
try again with iide/ldproxy:styles, that should be the most recent branch regarding vector tiles.
Best,
Andreas

**Comment by schmity** [comment]
Hi, 
tried iide/ldproxy:styles. 
There is no tiles section in the feature type config and I get HTTP 406 not acceptable when trying to view a service, e.g. at http://51.5.151.78:7080/rest/services/123/.

Is this really the right tag?

Best, 
Sebastian

**Comment by azahnen** [comment]
I guess you will need to adjust the config files manually, try to change the ```extensions``` property to the following and restart ldproxy:

```
"extensions" : {
	  "crsExtension": {
	    "extensionType" : "CRS",
	    "enabled" : true
	  }, 
	  "generalizationExtension": {
	    "extensionType" : "GENERALIZATION",
	    "enabled" : true
	  }, 
	  "geoJsonExtension": {
	    "extensionType" : "GEOJSON",
	    "enabled" : true
	  }, 
	  "gmlExtension": {
	    "extensionType" : "GML",
	    "enabled" : true
	  }, 
	  "htmlExtension": {
	    "extensionType" : "HTML",
	    "enabled" : true
	  }, 
	  "oas30Extension": {
	    "extensionType" : "OAS30",
	    "enabled" : true
	  }, 
	  "projectionsExtension": {
	    "extensionType" : "PROJECTIONS",
	    "enabled" : true
	  }, 
	  "stylesExtension": {
	    "extensionType" : "STYLES",
	    "enabled" : true,
	    "managerEnabled" : true,
	    "mapsEnabled" : true
	  }, 
	  "tilesExtension": {
	    "extensionType" : "TILES",
	    "enabled" : true,
	    "zoomLevels": {
	        "default": {
	          "max": 18,
	          "min": 6
	        }
	    },
	    "seeding": {
	        "default": {
	          "max": 0,
	          "min": 0
	        }
	    }
	  } 
  }
```

**Comment by schmity** [comment]
Hi,
which config file does that have to go into and to which property does it belong?
I tried xtraplatform.json and CoreServerConfig with no luck..

Best, Sebastian

**Comment by azahnen** [comment]
In `config-store/entities/services` should be files named like the service ids you chose. They should already have a property `extensions` which should be replaced with the one above.

**Comment by ghelle-fhh** [comment]
Hi there,
I'm having the same issue. 

I adjusted the file as per your instructions. However, I didn't see an existing extensions property in the file, so I added the extension property that you posted, but it's still not working unfortunately.

**Comment by schmity** [comment]
Hi,
I actually got a step further by adding the extensions property to the root of the config objects at config-store/entities/services - same level as id. 
However, the Tiles section on the OpenAPI page remains empty, even though tiles are seeded and served alright. I manually got the tile links from the json-tiles generated into ldproxy_data/tiles.

Any idea on the empty Tiles section on the OpenAPI page very much appreciated. 

Best, 
Sebastian

**Comment by azahnen** [comment]
I checked in a fix, if you pull the styles image again the OpenAPI stuff should work.

Just if you are not aware, this is unstable functionality and totally untested with legacy wfs as data source. We only use it for our demo at [https://services.interactive-instruments.de/vtp/](https://services.interactive-instruments.de/vtp/). These are manually configured services with postgres as data source. 
You can also checkout the styles extensions there, we use mapbox styles to render the tiles in an openlayers client (e.g. [https://services.interactive-instruments.de/vtp/daraa/maps/night](https://services.interactive-instruments.de/vtp/daraa/maps/night)).

**Comment by schmity** [comment]
Hi, 
great, that worked. We are totally aware of the unstableness, but prefer to show "our" data to introduce new concepts in our organization, 

best, sebastian
