### ISSUE TITLE
Running ldproxy within docker behind corperate proxy

### ISSUE THREAD

**Issue by lglref32team2** [interactive-instruments/ldproxy#142]
Hi all,
We are trying to set up a ldproxy instance using the provided docker image. The only problem is that we are behind a corporate proxy. I tried almost everything but I always get an UnknownHostException during the initialization of a service.  That exception is pretty much always caused by a missing proxy setting.
I set the Proxy for the docker and for the container and can access the internet from the containers command line by using the docker exec command. But the ldproxy is still not able to access any resources behind our proxy. I tried the same on my private computer and it works like a charm and is a very interesting and promising implementation for OpenAPI.
Therefore I wanted to ask if I'm missing any setting or if it is simple not possible to run ldproxy behind a corporate proxy.

Thanks in advance!
Alex

**Comment by azahnen** [comment]
Hi Alex,

the current stable release does not support http proxies. Version 2.0.0, which we are currently preparing, will support proxies. It should be released within the next month or so.

If you are interested I can give you the tag of a dev-image that already has this feature and the necessary configuration settings.

Hope that helps,
Andreas

**Comment by lglref32team2** [comment]
Hi Andreas,
thx for the quick answer. The tag of the dev-image would be awesome!
Regards,
Alex

**Comment by lglref32team2** [comment]
Hi Andreas,
sorry to bother you, but do you have the tag?
Thanks,
Alex

**Comment by azahnen** [comment]
Hi Alex,
sorry for the delay. When I tested this I found a bug I had to fix first.

You can use `iide/ldproxy:httpproxy`.  You have to configure the proxy in `cfg.yml` like this:

```
httpClient:
  proxy:
    host: localhost
    port: 8888
    scheme : http
```

**Comment by lglref32team2** [comment]
Hi Andreas,

thanks you a lot. I built it without problems but can't log in:
![grafik](https://user-images.githubusercontent.com/50007570/77887772-79dfd200-726b-11ea-97f8-826690606f6b.png)

I couldn't figure out how to set a user or if there is any default user.
Is it somehow possible?
Thanks,
Alex

**Comment by azahnen** [comment]
That looks like a bug, you should be logged in automatically. Doesn‘t it work if you click on Abbrechen? If not, try to delete all cookies for the domain.

**Comment by lglref32team2** [comment]
After deleting all the cookies the prompt still shows up but then after cancel the options appread!
Thanks a lot for your help!
