### ISSUE TITLE
create community modules repository

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#161]
Modules in ogcapi-experimental will no longer be part of ldproxy. Move them to a separate repository and design/describe a process to install them.

**Comment by cportele** [comment]
For ldproxy 2.0 simply remove these modules and add them to the community repo afterwards.

**Comment by cportele** [comment]
The modules have been moved. 

The nearby code in the html module (`FeatureTransformerHtml.java`, `FeatureCollectionView.java`, `featureDetails.mustache`) has been commented out for now.
