### ISSUE TITLE
security by default

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#164]
Enable security by default for ldproxy-manager, ldproxy-styles-manager and ldproxy-transactions.

**Comment by cportele** [comment]
... and for ldproxy-resources-manager

**Comment by cportele** [comment]
This is part of the manager update and will be shifted to v2.0.1 with the manager.

**Comment by cportele** [comment]
This includes updating the documentation wrt security aspects and configuration. Also test that all configuration options are properly reflected in the OpenAPI definition.

**Comment by azahnen** [comment]
- The default for all services is now `secured: true`. 
- If `secured: true`, all mutating operations require a valid token.
- If `secured: true`, the OpenAPI definition is adjusted accordingly. That also means the swagger-ui client shows an authorize button and restricted operations are marked.
