### ISSUE TITLE
improve extendable openapi definition

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#168]
Try to reduce redundancy. Increase clarity by using a declarative approach.

**Comment by cportele** [comment]
Currently the (JSON) schema of a resource is represented in the OpenAPI generation code, Java classes and sometimes other schemas for validation purposes. A general idea would be to use a JSON schema as the single source.

**Comment by cportele** [comment]
Still TODO:

- [ ] Sitemaps module
- [ ] A mechanism how to extend objects like the Collection object (e.g. from StyleInfo or Nearby/Around-Relations)
