### ISSUE TITLE
support temporal extent computation

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#174]
Add support for computing the temporal extent of a collection from the data, like for spatial extents.

**Comment by azahnen** [comment]
Methods to implement in xtraplatform-spatial:

- [ ] `FeatureProviderSql.getTemporalExtent(String typeName, String property)`
  Delegates to `ExtentReaderSql`, see `FeatureProviderSql.getSpatialExtent`.

- [ ] `FeatureProviderSql.getTemporalExtent(String typeName, String startProperty, String endProperty)`
  Delegates to `ExtentReaderSql`, see `FeatureProviderSql.getSpatialExtent`.

- [ ] `ExtentReaderSql.getTemporalExtent(FeatureStoreTypeInfo typeInfo, String property)`
  Delegates to `FeatureStoreQueryGeneratorSql`, see `ExtentReaderSql.getExtent`.

- [ ] `ExtentReaderSql.getTemporalExtent(FeatureStoreTypeInfo typeInfo, String startProperty, String endProperty)`
  Delegates to `FeatureStoreQueryGeneratorSql`, see `ExtentReaderSql.getExtent`.

- [ ] `FeatureStoreQueryGeneratorSql.getTemporalExtentQuery(FeatureStoreAttributesContainer attributesContainer, String property)`
  The generated query should look like this: `SELECT min(column), max(column) from table [optional joins];`

- [ ] `FeatureStoreQueryGeneratorSql.getTemporalExtentQuery(FeatureStoreAttributesContainer startAttributesContainer, FeatureStoreAttributesContainer endAttributesContainer, String startProperty, String endProperty)`
  When `startAttributesContainer` and `endAttributesContainer` are the same, the query would look like this: `SELECT min(startColumn), max(endColumn) from table [optional joins];`
  If they differ, it would look like this: `SELECT * FROM (SELECT min(startColumn) from startTable [optional joins]) AS A, (SELECT max(endColumn) from endTable [optional joins]) AS B;`

**Comment by azahnen** [comment]
Methods to implement in ldproxy:

- [ ] `CollectionExtent.getTemporalComputed`
  see `CollectionExtent.getSpatialComputed`

- [ ] `FeaturesCoreDataHydrator.hasMissingIntervals`
  see `FeaturesCoreDataHydrator.hasMissingBboxes`

- [ ] `FeaturesCoreDataHydrator.computeMissingIntervals`
  see `FeaturesCoreDataHydrator.computeMissingBboxes`

**Comment by azahnen** [comment]
Computation currently depends on the temporal queryables, see also #323.
