### ISSUE TITLE
Missing context information in log messages from the database (PostgreSQL)

### ISSUE THREAD

**Issue by rkoblenzer** [interactive-instruments/ldproxy#211]
If the database (PostgreSQL) is being shut down or restarted I get the following message in the logfile:

```
ERROR [2020-08-16 19:50:25,441] FATAL: Verbindung wird abgebrochen aufgrund von Anweisung des Administrators
```

I this case I knew the cause. But in general, I think, additional information about where the message came from would be very helpful (e.g. at least the provider id, maybe also something like "SQL" or "database").

**Comment by azahnen** [comment]
The message is now prefixed with `Unexpected SQL query error: `, the provider id was already added by former improvements.

**Comment by rkoblenzer** [comment]
Confirmed, error messages contain now additional context information.
