### ISSUE TITLE
add optional mapping validation on startup

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#260]
The provider should check on startup if the mapping and the database fit together. 

This check should be optional, meaning it can be enabled/disabled in the provider configuration. Additionally I would provide a configuration option to decide if a failed validation throws an error or just logs a warning.

**Comment by azahnen** [comment]
I added the option `validateTypes` with values `OFF`, `WARN` or `ERROR` to the provider configuration and the call to the validator on provider startup in branch `mapping-validation`. 
The actual validation should happen in class `SqlTypeInfoValidator`, it contains lots of todos.

**Comment by cportele** [comment]
The description of the options need to be added to the [documentation](https://github.com/interactive-instruments/ldproxy/tree/master/docs/de/configuration/providers).

**Comment by azahnen** [comment]
As discussed in #330 test for all value types should be added. As a prerequisite I did an in depth analysis of supported cases and potential issues. I am posting and editing it here, when this issue is closed it can be moved to the dev or user docs.

# SQL Mapping Guide

The type definitions in the provider configuration serve two purposes: they define the schema of the features provided to consumers and they define mappings between tables and columns in a database and the features and its properties. 

## Use cases

There are three use cases where the provider uses the mappings from the type definitions:

1.  Output (e.g. `SQL -> GeoJSON`)

    In this case the provider uses the mapping to generate SQL queries and to transform the query results into features with the defined schema.

2.  Filter (e.g. `CQL -> SQL`)

    In this case the provider uses the mapping to transform filter expressions based on the feature properties into SQL where clauses.

3.  Input (e.g. `GeoJSON -> SQL`) (transactions are future work)

    In this case the provider uses the mapping to transform features with the defined schema into SQL inserts.

**Note:** The _Input_ use case is not considered in the following, it should be discussed as part of the transactions revision. **Follow-up action 1**

## Structural Mappings

(Tables + Joins -> Objects + Arrays)

TBD 

## Value Mappings

A value mapping consist of, amongst other things, a property type given via `type` or `valueType` and a `sourcePath`. The latter represents a SQL column, which also has an implicit type. A value mapping is only valid if there is a way to transform values between these two types.

### Property types

-   `STRING`
-   `BOOLEAN`
-   `INTEGER`
-   `FLOAT`
-   `DATETIME`
-   `GEOMETRY`

### Use cases

The use cases described above apply to value mappings like this:

1.  Output

    In this case the provider reads a value from a SQL query result and has to transform it to the defined property type.

2.  Filter

    In this case the provider reads a value with the defined property type from a CQL expression and has to transform it to a SQL literal in the where clause. So this case needs the reverse transformation compared to the _Output_ case.

### Type combinations

Below you find a matrix for all combinations of property types and SQL types. The cells contain the following criteria, displayed by the symbols in parentheses.

1.  (1) can always be transformed, regardless of the data (e.g. `timestamp -> DATETIME`)
2.  (2) can be transformed if the data fulfills certain requirements

    A transformation of this type is either (n) narrowing (e.g. `string -> DATETIME`) or (w) widening (e.g. `timestamp -> STRING`) for _Output_. For _Filter_ it is the reverse.
    The problematic transformation type is narrowing, so combinations marked with (n) might fail for _Output_ and transformations marked with (w) might fail for _Filter_ (see _Error handling_ below).
3.  (3) cannot be transformed (e.g. `boolean -> DATETIME`)

Combinations that should work but were not yet tested and/or might need code adjustements are marked with (?).
Combinations that could work but are regarded as not supported at this time are marked with (!).

#### [PostgreSQL](https://www.postgresql.org/docs/12/datatype.html#DATATYPE-TABLE)/PostGIS

|                        Column type                        | STRING | BOOLEAN | INTEGER | FLOAT | DATETIME | GEOMETRY |
| :-------------------------------------------------------: | :----: | :-----: | :-----: | :---: | :------: | :------: |
| bigint, integer, smallint, bigserial, serial, smallserial |   2w   |   2n?   |    1    |   2w  |    1?    |     3    |
|                          boolean                          |   2w   |    1    |   2w?   |  2w?  |     3    |     3    |
|             character, character varying, text            |    1   |    2n   |    2n   |   2n  |    2n    |     3    |
|          date, timestamp, timestamp with timezone         |   2w   |    3    |    1?   |   3   |     1    |     3    |
|      double precision, decimal/numeric, real, money?      |   2w   |    3    |    2n   |   1   |     3    |     3    |
|                          geometry                         |    3   |    3    |    3    |   3   |     3    |     1    |
|                            uuid                           |   2w!  |    3    |    3    |   3   |     3    |     3    |
|                  time, time with timezone                 |   2w!  |    3    |    3    |   3   |     3    |     3    |
|                          interval                         |   2w!  |    3    |    3    |   3   |     3    |     3    |
|                    cidr, macaddr, inet                    |   2w!  |    3    |    3    |   3   |     3    |     3    |
|                         json, xml                         |   2w!  |    3    |    3    |   3   |     3    |          |
|               bit, bit varying, bytea, jsonb              |    3   |    3    |    3    |   3   |     3    |     3    |
|       box, circle, line, lseg, path, point, polygon       |    3   |    3    |    3    |   3   |     3    |     3    |
|              tsquery, tsvector, txid_snapshot             |    3   |    3    |    3    |   3   |     3    |     3    |
|                           arrays                          |    3   |    3    |    3    |   3   |     3    |     3    |

### Error handling

For type 2 mappings, errors might occur when transforming values.

1.  Output

    In this case (2n) transformations might fail. For example for the combination `text -> INTEGER`, a string needs to be transformed to an integer. If the string is not a valid number, the transformation will fail. Currently errors are not handled appropiately, see **Follow-up action 2**.

2.  Filter

    In this case (2w) transformations might fail. For example for the combination `integer -> STRING`, a string needs to be transformed to an integer. If the string is not a valid number, the transformation will fail. Currently errors are not handled appropiately, see **Follow-up action 3**.

## Geometry Mappings

TBD

# Follow-up actions

1.  Transactions revision: document relevant mapping constructs and add according validations.

2.  Value transformations for _Output_ are currently performed by the implementations of _FeatureTransformer2_, results will vary. For example when transforming a string to integer, the _FeatureTransformerGeoJson_ just ignores the error and writes the string to the output, so the resulting GeoJSON will not be conformant to the schema. 

    To handle transformation errors in a consistent and reliable way, the provider should be responsible for the transformations. This should be implemented as part of a redesign already planned in #190.

    When this centralized transformation handling is implemented, the desired action in case of an error can be made configurable. For example a non-mandatory property might be skipped or a configured default value might be returned. 

3.  Value transformations for _Filter_ are currently performed by the database as part of the query. As there is no way to differentiate this case from other query errors, it will result in a HTTP status 500.

    The best solution for such cases would be to automatically attach an implicit constraint to the property definition. The constraint could then be considered by the CQL parser and an invalid value could be rejected with HTTP status 400.

    Constraints are already supported by the provider, for this case an explicit constraint would look like this:

        constraints:
          regex: [0-9]+
