### ISSUE TITLE
support ogcapi extension startup/health checks

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#263]
The ogcapi service should ask every extension on startup if it has all the resources it needs, for example the feature core extension needs a feature provider. If the feature provider is not there, startup should fail. 

A related topic that should be considered is service hydration. Service hydration takes place before startup tasks and also delegates to extensions. Currently, if no feature provider is found and for example spatial extents should be computed, hydration fails but service seems to start normally.

So at least error handling during hydration has to be improved, but most likely startup checks should happen before or as part of the hydration.

We should also verify if it is easy to implement the same checks as dropwizard health checks. That would allow continuous monitoring of the service state at the admin endpoint at 7081.

**Comment by cportele** [comment]
closed by #362, open issues covered in #376, #377, #378, #379
