### ISSUE TITLE
improve sql logging

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#270]
Currently it is necessary to activate the `slick` logger to see sql queries. We should log sql queries under the `de.ii` logger on level `DEBUG`. For a user it should never be necessary to activate a third party logger to see relevant information.

Additionaly we need to make sure that when a query error happens it is clear which query caused the error, either through context or by including the query in the error message.

**Comment by azahnen** [comment]
I added configuration options for SQL logging, see https://github.com/interactive-instruments/ldproxy/commit/cee58c4bf82efee75946a4e9c0d11963d5aca386. I also improved the context for query error messages.

**Comment by rkoblenzer** [comment]
I tested the new logging options (`sqlQueries`, `sqlResults`, `stackTraces`and `configDumps`). It works as expected and it's useful.
