### ISSUE TITLE
Missing provider information in WFS capabilities

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#28]
schema.org requires values for provider/url, provider/contactPoint/url and provider/contactPoint/contactType, but the WFS capabilities may not include these (like in the PDOK WFSs).

**Comment by cportele** [comment]
no longer relevant - issue can be closed

**Comment by akuckartz** [comment]
Why "no longer relevant"?

**Comment by cportele** [comment]
I should have written "implemented" - the information can be configured for each API.
