### ISSUE TITLE
spatial extent not computed, if a temporal extent is provided?

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#286]
If one adds a temporal extent for a collection in the API configuration, `spatialComputed: true` does not seem to have an effect anymore and the collection no longer has a spatial extent.

**Comment by azahnen** [comment]
Can you provide more context? It seems to be working fine here: https://demo.ldproxy.net/daraa

**Comment by cportele** [comment]
I did not work when I looked at it and spatial extents were only reported after I added the `defaultExtent ` in the services configuration. Without it, no spatial extent was there, also for the collections with just a 5 features or so. Maybe I did not wait long enough? In that case we can close the issue.

**Comment by azahnen** [comment]
Maybe you tested it with the reload task? The extent is not computed after reload, I am working on a fix as part of #266.

Apart from that I could not find any reason when stepping through the code why setting a temporal extent might affect computation of the spatial extent.

**Comment by cportele** [comment]
Yes, I think, the reload option was active. So, I will close this for now.
