### ISSUE TITLE
feature id filters are rejected

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#298]
The ldproxy CQL grammar supports ID filters like ECQL does (e.g., `filter=IN (1,10,99)`). Internally a placeholder `_ID_` is used as a property name that is later replaced by the property name of the property with role ID. However, these queries are currently rejected, because `_ID_` is not a known queryable. Add `_ID_` to the list of valid properties when checking the filter expression.

**Comment by azahnen** [comment]
The internal placeholder is now ignored in the validation function in the CQL module.
