### ISSUE TITLE
various improvements to vector tiles and styles

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#310]
The following improvements in the support for vector tile and style resources have been identified:
* support hashes in the URLs of the Mapbox GL web maps
* allow non-word characters in style identifiers
* extract style title from stylesheets
* make repairing polygons more robust, avoid errors if that fails and just ignore the geometry; if a merged geometry is invalid, use the un-merged features
* reduce number of vertices in vector tile geometries using JTS simplifier
* log errors when building the tile transformation context

(This issue originally covered also other topics, which now have been moved to separate issues.)

**Comment by azahnen** [comment]
To get a clean changelog I think you should create separate issues at least for the 5 enhancements and the first bug. 
For the improvements and the second bug which also looks more like an improvement I think it would be fine to have a combined issue like `various improvements to tiles and styles`.

**Comment by cportele** [comment]
OK, I will create/update the issues.
