### ISSUE TITLE
Queryables and datetime/bbox

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#323]
Currently the order of the temporal queryables in the service configuration is relevant, if multiple queryables are specified. The first is the start and the second the end of an interval when the `datetime` parameter is used. 

This should be made explicit in the provider configuration using `INSTANT`, `START` and `END` as roles for the temporal properties. 

In case of multiple spatial properties, we also need a role like `PRIMARY` to identify the property that should be used for `bbox`.

**Comment by cportele** [comment]
related to #190 and #346

**Comment by azahnen** [comment]
I introduced `PRIMARY_GEOMETRY`, `PRIMARY_INSTANT`, `PRIMARY_INTERVAL_START` and `PRIMARY_INTERVAL_END` in #483.
