### ISSUE TITLE
Schema: Distinguish Date and DateTime properties

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#335]
Date and DateTime properties are both represented as DATETIME, so we cannot declare to the user / in the queryables / in the schema, whether a temporal property is a DateTime or a Date.

**Comment by cportele** [comment]
related to #190 and #346

**Comment by azahnen** [comment]
Support for type `DATE` is introduced in #483. A default `dateFormat` returning e.g. `2014-06-30` is applied by the provider if none is set by the user, also see #472.
