### ISSUE TITLE
check proper WFS operation and supported capabilities on service creation

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#37]
When adding a WFS, functionality like count, startindex or numberMatched, which ldproxy depends on, should be tested. The user can then be notified of the limitations and ldproxy can behave accordingly. E.g. it could just show the first page with deactivated pagination instead of showing a broken page.

Before that, general proper operation should be checked. Since we relaxed requirements on schema validity, many services do not work at all. 
Errors should be visible as notifications for the service and the service should be powered off permanently.

**Comment by azahnen** [comment]
We decided to wait with the implementation of this issue until a decision regarding the elise branch was made. The reason is that we would have to reimplement parts of the code in the elise branch and potentially merge the two implementations again later on.

**Comment by cportele** [comment]
#78 addresses the schema issue

**Comment by cportele** [comment]
since WFS backends are becoming less important I am closing the issue
