### ISSUE TITLE
replace all field injections with constructor injections

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#376]
Field injections are generally considered an anti-pattern, as they make instantiating classes in a context without a dependency injection container much harder (e.g. in unit tests). With iPOJO there might also be issues with null injections when using field injections.

Therefore we should replace all field injections with constructor injections. A technical issue in this context (which is the reason why we used field injection in the first place in some cases) is that constructor injections are only allowed for interfaces. So if a class without interface is injected into a field, an interface has to be extracted before refactoring to constructor injection.

Tasks:

- [x] search for every occurrence of `@Requires` in ldproxy, xtraplatform-spatial and xtraplatform
- [x] if `@Requires` annotates a field and the field type is a class, extract an interface and use that instead (right click -> Refactor -> Extract Interface in Intellij)
- [x] replace field injection ([example](https://github.com/interactive-instruments/ldproxy/blob/ec68c9f8997da462cfa8b60f49207ba36bf7a7a6/ogcapi-draft/ogcapi-observation-processing/src/main/java/de/ii/ldproxy/ogcapi/observation_processing/application/ObservationProcessingOnLandingPage.java#L33)) with constructor injection ([example](https://github.com/interactive-instruments/ldproxy/blob/ec68c9f8997da462cfa8b60f49207ba36bf7a7a6/ogcapi-draft/ogcapi-observation-processing/src/main/java/de/ii/ldproxy/ogcapi/observation_processing/application/ObservationProcessingOnLandingPage.java#L39))

**Comment by bekakh** [comment]
@azahnen - Should `@Context` field injections also be replaced by constructor injections?

**Comment by cportele** [comment]
addressed by #401
