### ISSUE TITLE
manager/ UI elements are missing

### ISSUE THREAD

**Issue by ndkv** [interactive-instruments/ldproxy#38]
Hi, 

the UI elements at `manager/` are missing? Any idea why?

![screenshot 2016-04-22 11 11 11](https://cloud.githubusercontent.com/assets/778666/14737183/130d9976-087b-11e6-9336-9c83d2fe8b44.png)

The `Settings` tab is empty as well. 

Adding and querying services through `/rest/services/` works fine. 

I'm running ldproxy on OS X through 

    docker run -d -p 7080:7080 -v ldproxy_data:/ldproxy/data -w /ldproxy iide/ldproxy

**Comment by azahnen** [comment]
Hi Simeon,

that is an open bug: #12 I will try to fix it soon, but it would not allow you to do much besides deleting services. 

There is another open issue, #14, which would allow you to edit the mapping from GML to schema.org in the UI.

**Comment by ndkv** [comment]
Ah, I missed #12. Is there another way of removing services? I want to get rid of the first one here: http://wfs2rest.ndkv.nl/rest/services/

**Comment by azahnen** [comment]
For now you have to delete the file /var/lib/docker/volumes/ldproxy_data/_data/config-store/ldproxy-services/rvim and then restart the container.

**Comment by ndkv** [comment]
I'll do that, thanks for the quick reply!

BTW, it's really great to explore the WFS endpoint in the browser!
