### ISSUE TITLE
limit/offset ignored in some queries

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#381]
In some cases the `limit`/`offset` values are ignored and all matching features are returned by FeatureSourceStream of the feature provider. This is at least the case with OR predicates.

Example: https://demo.ldproxy.net/vineyards/collections/vineyards/items?filter=subregion%20LIKE%20%27%25Bernkastel%25%27%20OR%20village%20LIKE%20%27%25Bernkastel%25%27%20OR%20searchfield2%20LIKE%20%27%25Bernkastel%25%27&limit=2

**Comment by azahnen** [comment]
The parentheses around the OR expression were missing, so limit/offset (which is also implemented as filter expression) became optional in this case.
