### ISSUE TITLE
add feature type abstracts to overview page

### ISSUE THREAD

**Issue by ndkv** [interactive-instruments/ldproxy#39]
Exploring the endpoint (for the first time) will be easier as users can quickly scan/search the abstracts for keywords they are interested in. 

Bonus: a download link/button that gives the whole dataset in GeoJSON + lat/lng. This is difficult to implement as, among many other reasons, many WFS serve a max. number of features. 

Ideally one would search for data through a catalog but sometimes it's as convenient or quicker to have a simple list of data.

**Comment by ndkv** [comment]
A feature type's abstract should be added to [this](https://github.com/interactive-instruments/ldproxy/blob/45ce117e4ca560e69e6252d78704f0ca3c3085e9/ldproxy-service/src/main/resources/de/ii/ldproxy/output/html/service.mustache#L15) template, right? How is it called? `{{abstract}}`?

**Comment by pvgenuchten** [comment]
The abstract would be extracted from wfs-capabilities, and/or would ldproxy grab the metadata linked to the featuretype and visualise some of those properties here

**Comment by cportele** [comment]
The idea with the download button has been added as a new issue #77.

NB: The feature abstract is extracted from the capabilities.

**Comment by cportele** [comment]
implemented - issue can be closed
