### ISSUE TITLE
Update Filtering/CQL to Part 3, 1.0.0-draft.2

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#395]
Part 3, 1.0.0-draft.2 (in public review): https://portal.ogc.org/files/?artifact_id=96288&version=2

* [x] The BNF has been updated in general and we should sync with the current grammar. Updated BNF: https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/standard/schema/cql.bnf. Important changes in predicates:
  * LIKE operator has additional options and by default comparisons are case insensitive
  * Array expressions have been added: https://docs.ogc.org/DRAFTS/19-079r1.html#arrays
  * Support double quoted identifiers (`doubleQuote`)
  * A boolean literal has been added
  * axis order of coordinates in ENVELOPE has changed (to align with bbox parameter)
  * Note: We won't implement any other parts of CQL that were excluded in the initial implementation
* [x] Keywords in the BNF grammar are case-insensitive. I.e., "and", "AND", "aNd" etc. all match "AND". This is a general rule for ABNF grammars. Currently, they the implementation is case sensitive. 
* [x] A query parameter `filter-crs` must be supported: https://docs.ogc.org/DRAFTS/19-079r1.html#filter-filter-crs

**Comment by azahnen** [comment]
### Implementation tasks:

- **case insensitive keywords** 
  - [ ] define keywords in `CqlLexer.g4` as described [here](https://github.com/antlr/antlr4/blob/master/doc/case-insensitive-lexing.md#case-insensitive-grammars)
- **filter-crs**
  - [x] our CQL text parser already accepts a CRS parameter, currently it is always set to CRS84
  - [ ] add `read` method with additional CRS parameter in `Cql`/`CqlImpl`, pass to `CqlTextParser.parse`
  - [ ] add `QueryParameterFilterCrs`, read and pass to `CQL.read` in `FeatureQueryImpl`
- **double quoted identifiers**
  - [ ] adjust grammar in CqlLexer.g4`  
- **axis order of coordinates in ENVELOPE has changed**
  - [ ] adjust grammar in CqlParser.g4`  
- **LIKE operator has additional options**
  - [ ] adjust grammar in CqlParser.g4` and domain model
- **Array expressions** TBD
- **general**
  - the [BNF definition](https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/standard/schema/cql.bnf) has changed significantly, but I am not sure to which extent that really changes the resulting grammar, so I would follow these steps:
  - [ ] check the current CQL text [examples](https://github.com/opengeospatial/ogcapi-features/tree/master/extensions/cql/standard/schema/examples), adjust the existing tests in `CqlTextSpec`, add missing tests
  - [ ] adjust the grammar to make the tests pass

**Comment by cportele** [comment]
> the BNF definition has changed significantly, but I am not sure to which extent that really changes the resulting grammar

In general, it should be the same (except in the cases that I have identified, although I may have missed something). The changes we mainly required for consistency between the BNF grammar and the schema for the JSON encoding, which required a re-factoring: https://github.com/opengeospatial/ogcapi-features/issues/460.

**Comment by cportele** [comment]
I also noticed that `ANYINTERACTS` is not implemented, but it is mandatory, so this needs to be supported, too.

In general, we should implement all the temporal operators and align the implementation with the spec, but this can be a second step. For example, `After` only works with instants or `TOverlaps` is not the operator specified in the spec.

**Comment by cportele** [comment]
I found another difference. Currently predicates where both operands are property references (e.g. `height < floors`) are not supported, but this is required by CQL.

**Comment by cportele** [comment]
We should decouple array predicates from this issue, I have created #431.

**Comment by cportele** [comment]
closed by #423

**Comment by cportele** [comment]
Open issues are in #432.
