### ISSUE TITLE
configurable handling of multiplicity

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#4]
Could me mapped as list or reduced to a limited number. The latter could still be a list or multiple properties.
Do we want to support all variants?

**Comment by azahnen** [comment]
I implemented a very simple solution that does not rely on the schema. Whenever a property occurs more than once in the json output, a suffix with the number of occurrence is added to the field name.

**Comment by cportele** [comment]
implemented - issue can be closed
