### ISSUE TITLE
COMPLEX_OBJECTS layout incompatible with WFS providers

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#414]
The COMPLEX_OBJECTS layout is not able to generate schema.org annotations for GML from WFS providers unless all geometries have a srsDimension attribute. This can be fixed by using the same code as for the CLASSIC layout.

**Comment by mattenp** [comment]
Hi,
what do you mean by using the classic layout?
Here are complex objects, segments (geometries) inside of a baseline (theme INPIRE Maritime Units)

`types:
  baseline:
    sourcePath: /mu:Baseline
    type: OBJECT
    properties:
      id:
        sourcePath: gml:@id
        type: STRING
        role: ID
      beginLifespanVersion:
        sourcePath: mu:beginLifespanVersion
        type: DATETIME
        role: PRIMARY_INSTANT
      endLifespanVersion:
        sourcePath: mu:endLifespanVersion
        type: DATETIME
      inspireId:
        sourcePath: mu:inspireId/base:Identifier
        type: OBJECT
        properties:
          localId:
            sourcePath: base:localId
            type: STRING
          namespace:
            sourcePath: base:namespace
            type: STRING
          versionId:
            sourcePath: base:versionId
            type: STRING
      segment:
        sourcePath: mu:segment/mu:BaselineSegment
        type: OBJECT_ARRAY
        properties:
          geometry:
            sourcePath: mu:geometry`

From logfile:

OBJECT NOT FOUND mu:Baseline.mu:segment.mu:BaselineSegment.mu:geometry [[mu:Baseline], [mu:Baseline, gml:@id], [mu:Baseline, mu:beginLifespanVersion], [mu:Baseline, mu:endLifespanVersion], [mu:Baseline, mu:inspireId, base:Identifier], [mu:Baseline, mu:inspireId, base:Identifier, base:localId], [mu:Baseline, mu:inspireId, base:Identifier, base:namespace], [mu:Baseline, mu:inspireId, base:Identifier, base:versionId], [mu:Baseline, mu:segment, mu:BaselineSegment], [mu:Baseline, mu:segment, mu:BaselineSegment, mu:geometry], [mu:Baseline, mu:segment, mu:BaselineSegment, mu:segmentType], [mu:Baseline, mu:segment, mu:BaselineSegment, mu:segmentType, xlink:@title], [mu:Baseline, mu:segment, mu:BaselineSegment, mu:segmentType, xlink:@href]]
Invalid request: Could not parse GML: For input string: "DE_0SM_NS100L" [67007e6f-8885-48b4-8c10-41bb682bbaf7]
accept text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8 [67007e6f-8885-48b4-8c10-41bb682bbaf7]
Client error, HTTP status 400, Request path /MU_INSPIRE/collections/baseline/items: Could not parse GML: For input string: "DE_0SM_NS100L" [67007e6f-8885-48b4-8c10-41bb682bbaf7]


Best regards,

Matthias

**Comment by cportele** [comment]
This (very old) issue was about the [`layout` option](https://docs.ldproxy.net/services/building-blocks/features_-_html.html#options) in the FEATURES_HTML building block. `CLASSIC` refers to a small map on the right side and features with their attributes on the left side. `COMPLEX_OBJECTS` had the map on top and the features/attributes below and using the full width of the page. 

In any case, that option is deprecated and will no longer be included in ldproxy 4.0.

But your problem does not seem related to this issue anyhow.
