### ISSUE TITLE
provide 2 semantic definitions for a feature attribute

### ISSUE THREAD

**Issue by pvgenuchten** [interactive-instruments/ldproxy#44]
would it be an option to provide for a single encoding 2 semantic definitions for the same feature attribute, for example a feature attribute could be a http://schema.org/postOfficeBoxNumber as well as https://raw.github.com/doroam/planning-do-roam/master/Ontology/tags.owl#k_addr:housenumber

**Comment by cportele** [comment]
The JSON-LD module has been removed. 

But in general this is an issue in JSON-LD that one can map a member to only one definition (unlike the object that can have multiple @type values).
