### ISSUE TITLE
display links to linked features as html-links

### ISSUE THREAD

**Issue by pvgenuchten** [interactive-instruments/ldproxy#45]
on the kadaster address service, this feature

http://dev.ldproxy.net/rest/services/nl_ad/Address/NL.KAD.BAG.AD.Address.10200000100502/

It looks not that informative, mostly because the link to ThoroughfareName is not displayed 

http://geodata.nationaalgeoregister.nl/inspire/ad/wfs?request=GetFeature&version=2.0.0&typeName=ad:ThoroughfareName&FEATUREID=NL.KAD.BAG.AD.ThoroughfareName.10300000000628

Is this a missing feature in ldproxy or are there misconfigurations on the service which prevent these links to be displayed?

**Comment by azahnen** [comment]
The feature is missing, will be implemented in #50
