### ISSUE TITLE
SQL error from valid bbox filter

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#468]
```
SELECT AA.ogc_fid FROM aixm AA  WHERE ST_Intersects(AA.wkb_geometry, ST_GeomFromText('POLYGON((-142.44685292819156 6.937098414839057,-65.05897890126143 6.937098414839057,-65.05897890126143 56.141938550802685,-142.44685292819156 56.141938550802685,-142.44685292819156 6.937098414839057))',4326))
```

works, but 

```
SELECT A.ogc_fid AS SKEY FROM aixm A WHERE A.ogc_fid IN (
   SELECT AA.ogc_fid FROM aixm AA  WHERE ST_Intersects(AA.wkb_geometry, ST_GeomFromText('POLYGON((-142.44685292819156 6.937098414839057,-65.05897890126143 6.937098414839057,-65.05897890126143 56.141938550802685,-142.44685292819156 56.141938550802685,-142.44685292819156 6.937098414839057))',4326))
)
```

results in the following error:

`SQL Error [XX000]: ERROR: Geometry could not be converted to GEOS: IllegalArgumentException: Invalid number of points in LinearRing found 2 - must be 0 or >= 4`

Request: https://t17.ldproxy.net/airports2/collections/LAX/items?bbox=-142.44685292819156,6.937098414839057,-65.05897890126143,56.141938550802685

**Comment by azahnen** [comment]
The issue here is not the given bbox, but the geometries in the database. The following query shows that there are 12 rows in aixm with invalid polygons:

```
SELECT ogc_fid, ST_NPoints(wkb_geometry), ST_AsText(wkb_geometry) FROM aixm WHERE ST_GeometryType(wkb_geometry) = 'ST_Polygon' AND ST_NPoints(wkb_geometry) < 4
```

After deleting these rows, both queries work as expected (for me, both queries failed before, not just the second).

**Comment by cportele** [comment]
Thanks for the analysis, @azahnen, good that it is the data and not (really) the GEOS code. I will clean the data.
