### ISSUE TITLE
add admin task to purge files from a tile cache

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#469]
Options:

* the API (mandatory)
* a tile matrix set to select the tile sets to purge (default: purge tile sets for all tile matrix sets) 
* a collection to select the tile sets to purge (default: purge tile sets for all collections as well as the dataset tile sets); the dataset tile sets will always be purged, too
* a WGS84 bbox to select the tiles per zoom level in each tile set (default: no spatial filter, all tiles per zoom level)

The TileCache class already includes methods for purging (via #470), but those methods need testing (and tests).

**Comment by azahnen** [comment]
I implemented an admin task that just passes the (validated) parameters to `TileCache.deleteTiles`. Example:

```
curl -X POST "http://localhost:7081/tasks/purge-tile-cache?api=vineyards&collection=vineyards&tileMatrixSet=WebMercatorQuad&bbox=8,49,9,50"

```

**Comment by cportele** [comment]
The issue will be closed after more testing.

**Comment by azahnen** [comment]
I added support in `xtractl`: https://github.com/interactive-instruments/xtraplatform-cli/releases/tag/v1.1.0

**Comment by cportele** [comment]
All tasks have been implemented and tested
