### ISSUE TITLE
schema parser does not support all types

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#47]
e.g. http://dev.ldproxy.net/manager/#/services/alkis_nw/AX_Gebaeude
- zeigtAufExternes
- qualitaetsangaben

**Comment by azahnen** [comment]
There were actually two issues. First, some mapped property names for nested properties were messed up, and second, some properties did not show up at all.
The reason for the second issue is that the schema parser uses a whitelist of GML types. Properties of any other type are ignored. In this case there were several properties of type anyURI.

The adjusted whitelist looks like below, we should discuss if any other relevant types are missing:
- ID
- string
- dateTime
- date
- decimal
- double
- float
- int
- integer
- long
- short
- boolean
- anyURI

**Comment by cportele** [comment]
The types listed above seem to be XML Schema types only, not GML types.

The list seems to cover the most common XML Schema data types, but of course others like time, duration, gYear, base64Binary, nonNegativeInteger, etc. could be used, too.

GML also defines a number of types with simple content, that must be supported, the most common ones are:

* ReferenceType
* MeasureType (and all the sub-types like LengthType)
* CodeType
* CodeWithAuthorityType

There are many more types and GML application schemas may also define types with simple content.

**Comment by cportele** [comment]
At this point this is just a placeholder. We close this and if the need for additional type support appears a new issue can be created.
