### ISSUE TITLE
Data is not found, but there are no error messages

### ISSUE THREAD

**Issue by hhmric** [interactive-instruments/ldproxy#493]
Hi!
For setting up my API, I followed the vineyard guide, so configured everything in the same way. The only difference is that the database has not been downloaded, but is only connected to. The connection works fine, the types are written into the providers config.
When I open the rest/services/service_name page, no data is available, it says: Data: None
Unfortunately, I do not get any error messages, so it is hard to say what could be wrong.

I would be very happy about any ideas/advices.
Thanks!

**Comment by cportele** [comment]
Were you able to resolve the issue? 

The vineyard guide probably needs an update to the latest version. If you have any further info on the issue it would be good to know so we can address it in the documentation. Thanks.

**Comment by cportele** [comment]
Great. Thanks for the explanation / update.
