### ISSUE TITLE
Support for Maps (based on Vector Tiles and Styles)

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#498]
Render PNGs on the server based on the configured styles and Vector Tiles, delivery via Tiles API.

The rendering software (likely tileserver-gl) would run in its own Docker container, communicating via HTTP, with access to the vector tiles.

Notes:

* Tiling scheme is WebMercatorQuad, maps, e.g., in ETRS89/UTM32 cannot be supported directly.
* For tiles with text labels, the labels are partly cut off at the tile border, but the effect can be significantly reduced with symbol-avoid-edges.

**Comment by cportele** [comment]
These changes build on PR #492 which adds general support for bitmap tiles.

Map tiles in WebMercatorQuad will be supported using a single style. There is currently no specification (or conflicting drafts) how to support multiple styles, in particular, if the API also supports OGC API Styles, but the styles are not identical to the map styles. Supporting multiple map styles will have to wait until these issues have been resolved.

* Since map tiles are a concept that is defined in OGC API styles, we will add the capability in the TILES building block.
* In TilesConfiguration a new option `mapProvider` will be added. Currently there is only one subtype "TILESERVER".
  * The only configuration options beside the `type` are
    * `urlTemplate` (string, mandatory, no default): a URL template for the access to the map tile from the tileserver-gl deployment. The URL template must include the parameters `tileMatrix`, `tileRow`, `tileCol` and `format`;
    * `tileEncodings` (string array, default is ["PNG"]) with "PNG", "JPG" and "WEBP" as recognized values.
* Tiles can be provided on the dataset (multi-collection, base path is `/`, the landing page) or on the collection level (base path `/collections/{collectionId}`).
* If TILES is enabled for the dataset or a single collection AND a map provider has been configured, the following resources will be made available relative to the base path, currently with WebMercatorQuad as the only supported `tileMatrixSetId`:
  * `/map/tiles`
  * `/map/tiles/{tileMatrixSetId}` 
  * `/map/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}`
* `/map/tiles`: Return the same information as for `/tiles`, reduced to WebMercatorQuad and links adjusted to the map URIs.
* `/map/tiles/{tileMatrixSetId}`: Same, but for `/tiles/{tileMatrixSetId}`
* `/map/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}`: Fetch and return the map tile from the URL template for the requested format (or the tile cache, if the map tile has not been cached yet). Store the map tile in the tile cache. There must be a separate tile cache for each format in tileEncodings.

The [tileserver-gl](https://tileserver.readthedocs.io/en/latest/) deployment is a separate, independent component that must be configured correctly:

* The style used in the urlTemplate must use the proper tile source. If ldproxy uses a mbtiles tile provider, the same mbtiles file must be configured as the tile source in tileserver-gl, if ldproxy uses a features tile provider, the MVT tile URL template of ldproxy must be configured as the tile source in tileserver-gl.

**Comment by cportele** [comment]
Example configuration:

```yaml
- buildingBlock: MAP_TILES
  enabled: true
  mapProvider:
    type: TILESERVER
    urlTemplate: 'http://localhost:8080/styles/daraa-topographic/{tileMatrix}/{tileCol}/{tileRow}@2x.{fileExtension}'
    tileEncodings:
      - PNG
      - WebP
```

This enables the tiles under `/map/tiles`.

To enable the tiles under `/collections/{collectionId}/map/tiles` the option `urlTemplateSingleCollection` needs to be configured. It may contain the template `{collectionId}`, e.g.: 


```yaml
    urlTemplateSingleCollection: 'http://localhost:8080/styles/daraa-{collectionId}-topographic/{tileMatrix}/{tileCol}/{tileRow}@2x.{fileExtension}'
```

**Comment by bekakh** [comment]
Example configuration that uses a `.mbtiles` archive as a data source:

```
{
  "styles": {
    "topographic": {
      "style": "topographic.json",
      "tilejson": {
        "type": "overlay",
        "bounds": [35.7550727, 32.3573507, 37.2052764, 33.2671397]
      }
    }
  },
  "data": {
    "zoomstack": {
      "mbtiles": "daraa.mbtiles"
    }
  }
}
```

**Comment by cportele** [comment]
Tests completed, so we can close the issue, but this should be considered an experimental capability.
