### ISSUE TITLE
allow attribute mapping

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#50]
Attributes are ignored in general, besides the features gml:id, because they are often not relevant and might enlarge the mapping tree significantly.
The goal of this task is to at least allow mapping of xlink:href attributes. Additionally it would be great to have a global whitelist of attributes that are included in mappings. That list should be configurable in the manager.

**Comment by cportele** [comment]
WFS backends are now less important, we close this issue
