### ISSUE TITLE
add tile matrix sets for ETRS89/UTM32

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#505]
* AdV tiling scheme
* AdV tiling scheme extended to European coverage (used by BKG)
* GDI-DE tiling schema

**Comment by hhmric** [comment]
Hi! This is an interesting issue for me, as I am wanting to use a TMS which does not follow any standards. How likely/feasible would it be to include a possibility to configure a complete custom TMS? I have seen it in other software and I think it would be a very handy function. It would be great if you could share your opinion on that!
Thanks!

**Comment by cportele** [comment]
That should not be complicated to support, at least for "regular" tile matrix sets that can be specified by using a number of parameters. It would be more complex for cases which require use of TMS-specific formulas.

**Comment by hhmric** [comment]
That sounds great! The customizable parameters would be the same parameters used for the definition of other TMS (just as they are defined in Annex D of this document: https://docs.opengeospatial.org/is/17-083r2/17-083r2.html#62).
So it would be optimal if those parameters could be configured individually for every zoom level.
