### ISSUE TITLE
Add option to disable ST_ForcePolygonCCW() wrapper

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#506]
Currently geometries are requested in the PostGIS feature provider with a `ST_ForcePolygonCCW()` wrapper to ensure correct winding order in polygon rings. However, this results in incorrect geometries for solids as the view is not always from the top.

An option in the feature schema needs to be added to suppress the wrapper on geometry properties.

**Comment by azahnen** [comment]
@cportele In `xtraplatform-spatial` version `5.0.0-sql-queries-SNAPSHOT` I added the option `forcePolygonCCW` to `FeatureSchema`, which is `true` by default.

**Comment by cportele** [comment]
Tested and it works as expected.
