### ISSUE TITLE
Update Manager to changes in configuration options

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#533]
Several configuration options that are currently included in the Manager were deprecated and replaced by other mechanisms or options. These should be updated.

**Comment by codehub-rony** [comment]
Does this include the toggle for enabling Vector Tiles for a service? Currently the frontend of manager goes blank when vector tiles are enabled.

**Comment by cportele** [comment]
@codehub-rony

The Manager is now deprecated, will not be updated anymore and will be removed with version 4.0 (in Q1 2024). Keeping the Manager and its UI up-to-date with all other developments and configuration options was simply too much work for the value that the Manager offers.

It will be replaced by a new tool (Editor), which is a VS Code extension for generating and editing (with syntax checks and auto-completion) ldproxy YAML files. A preview supporting the auto-generation capabilities should be available in the next weeks.

Sorry, we should have already updated this is issue and added this information.

**Comment by azahnen** [comment]
Closing, see #1116.
