### ISSUE TITLE
Editing keywords in Manager results in large keyword lists

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#534]
When editing the default keywords in the Manager, the list of keywords in the yaml configuration file just grows with each keyword listed many times. After a few edits the size was already 82MB. This resulted in Java Heap Space errors of the server.

This should be fixed and we should check, if a similar behaviour of the Manager can occur in other places, too.

**Comment by azahnen** [comment]
I could not reproduce the issue, it works as expected for me. Can you provide the steps that trigger the issue for you?

**Comment by cportele** [comment]
I will try over the weekend. We will close this, if I fail...

**Comment by cportele** [comment]
I could not reproduce the behaviour. I know it had to do with copy/pasting some comma-separated values, but I in my tests now it worked fine.
