### ISSUE TITLE
allow embedding and mapping of referenced features

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#54]
For the mapping of xlink:href attributes there should be an additional (mime-type agnostic) field to provide the type(s) of features that should be embedded.
The mapping for these types would be copied into the mapping of the current type and property.

The GetFeature requests would then use resolveXlinkDepth when available. Of course this collides with the streaming approach, because the additional objects are appended to the feature collection and not embedded in place of the hrefs.

**Comment by cportele** [comment]
Partly implemented
