### ISSUE TITLE
Re-factor documentation of the ldproxy configuration options

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#578]
Current situation:

* The ldproxy configuration options are documented in markdown pages that are edited manually in both German and English. English is outdated and incomplete. 
* Managing the documentation separate from the code is complex and prone to inconsistencies.
* The information is needed in the Manager, too.

Move the German and English documentation of the options to Javadoc comments in the code.

**Comment by azahnen** [comment]
**Part 1**

For every file in https://github.com/interactive-instruments/ldproxy/tree/master/docs/en/configuration/services/building-blocks and https://github.com/interactive-instruments/ldproxy/tree/master/docs/de/configuration/services/building-blocks:

1. Find the matching derivation of [ApiBuildingBlock](https://github.com/interactive-instruments/ldproxy/blob/master/ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/ApiBuildingBlock.java) (e.g. [CapabilityCommon](https://github.com/interactive-instruments/ldproxy/blob/master/ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/domain/CapabilityCommon.java) for [common.md](https://github.com/interactive-instruments/ldproxy/blob/master/docs/en/configuration/services/building-blocks/common.md))
2. Rename from `CapabilityXXX` to `XXXBuildingBlock`
3. Add a javadoc comment to the class with the main paragraph from the markdown files using `@title`, `@en` and `@de` tags. 
4. Add `@see` tags for the matching derivation of [ExtensionConfiguration](https://github.com/interactive-instruments/ldproxy/blob/master/ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/ExtensionConfiguration.java) as well as for the derivations of [Endpoint](https://github.com/interactive-instruments/ldproxy/blob/master/ogcapi-stable/ogcapi-foundation/src/main/java/de/ii/ogcapi/foundation/domain/Endpoint.java) matching the resources from the table in the markdown files. (For an example, see [CommonBuildingBlock](https://github.com/interactive-instruments/ldproxy/blob/36f52dcba48876ac27b6bc84b69110824043838e/ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/domain/CommonBuildingBlock.java).)
5. Add a javadoc comment to the configuration class with the example(s) from the markdown files in `@example` tags.
6. Add a javadoc comment to every getter in the configuration class with the descriptions and defaults from the markdown configuration table using `@en`, `@de` and `@default` tags. (For an example, see [CommonConfiguration](https://github.com/interactive-instruments/ldproxy/blob/36f52dcba48876ac27b6bc84b69110824043838e/ogcapi-stable/ogcapi-common/src/main/java/de/ii/ogcapi/common/domain/CommonConfiguration.java).)

**Comment by azahnen** [comment]
**Part 2**

- Transfer the markdown from `building-blocks/README` (without the overview table) and `building-blocks/general-rules` to `ApiBuildingBlock`.
- Transfer the markdown from `services/README` to `OgcApiDataV2` and its super classes or property classes.
- Transfer the markdown from `codelists/README` to `CodelistData` and its super classes or property classes.
- Transfer the markdown from `providers/README` to `FeatureProviderDataV2` and its super classes or property classes.
- Transfer the markdown from `providers/sql` to `FeatureProviderSqlData` and its super classes or property classes.
- Transfer the markdown from `providers/wfs` to `FeatureProviderWfsData` and its super classes or property classes.
- Transfer the markdown from `providers/transformations` to `PropertyTransformation`.
- Transfer the markdown from `global-configuration` to `AppConfiguration` and its super classes or property classes.
