### ISSUE TITLE
Basemap duplicated in the maplibre clients in html format

### ISSUE THREAD

**Issue by tevbrasch** [interactive-instruments/ldproxy#588]
There appears to be an issue with the basemap representation (the map is duplicated) in the maplibre clients within the items and item html representations.

items: https://ogcapitest.kartverket.no/ldproxy/rest/services/kulturmiljoer/collections/kulturmiljo/items 
item: https://ogcapitest.kartverket.no/ldproxy/rest/services/kulturmiljoer/collections/kulturmiljo/items/1?f=html 

Html buildingblock we're using is:

- buildingBlock: HTML
  enabled: true
  noIndexEnabled: false
  schemaOrgEnabled: true
  collectionDescriptionsInOverview: true
  legalName: Legal notice
  privacyName: Privacy notice
  basemapUrl: https://opencache.statkart.no/gatekeeper/gk/gk.open_gmaps?layers=topo4&zoom={z}&x={x}&y={y}
  basemapAttribution: '&copy; <a href="https://www.kartverket.no" class="link0" target="_new">Kartverket</a>
    (2020), <a href="https://kartkatalog.geonorge.no/metadata/kulturminner-kulturmiljoeer/17adbcac-bbb2-4efc-ab51-756573c8f178"
    class="link0" target="_new">Datakilde</a>; &copy; Riksantikvaren'

**Comment by cportele** [comment]
Thanks @tevbrasch for reporting! It indeed looks as if basemap tiles are loaded twice. We will have a look for the cause.
