### ISSUE TITLE
WGS4 features: inverted lat-lon?

### ISSUE THREAD

**Issue by swiss-knight** [interactive-instruments/ldproxy#589]
Follow up on #587
I noticed that all my features, which are encoded in WGS84 in the database, and are correctly displayed, e.g. in pgAdmin, or QGIS :

![image](https://user-images.githubusercontent.com/19967599/151609026-88174ec9-58ea-4d33-9390-21db8e4dfc73.png)

but they are not displayed at the correct location on the minimap within the ldproxy REST service, e.g. 
when I reach `http://my-base-server.ch:7080/rest/services/myservice/collections/countries/items/156?f=html` the minimap is just a light gray rectangle.

And when I copy/paste the corresponding GeoJSON feature (Lichtenstein country border, see hereunder) from the equivalent JSON query: `http://my-base-server.ch:7080/rest/services/myservice/collections/countries/items/156?f=json` in [geojson.io](https://geojson.io/), it is placed in Somalia, mirrored _and_ rotated 90°:

![image](https://user-images.githubusercontent.com/19967599/151609110-24d5c0e1-8ac1-4c0a-a353-e07ed3e6c925.png)

Here is the GeoJSON feature coming from  `http://my-base-server.ch:7080/rest/services/myservice/collections/countries/items/156?f=json`: 

```
{"type":"Feature","id":156,"geometry":{"type":"Polygon","coordinates":[[[47.05687042300007,9.58120284000003],[47.08077077300007,9.608798055000136],[47.10676401800003,9.615722697000109],[47.13226633700006,9.605594116000077],[47.15490061500009,9.5818229570001],[47.16688954700007,9.552057332000118],[47.17557118800001,9.551953979000103],[47.190609029000115,9.561875854000078],[47.19774037700006,9.562909383000061],[47.21161549900012,9.554331095000123],[47.22032297800007,9.544822632000148],[47.229107972000065,9.540378458000134],[47.243034770000065,9.547096395000068],[47.25365427700004,9.530249878000092],[47.262801005000114,9.52115482500011],[47.243732402000035,9.504618368000138],[47.210013529000065,9.487358439000047],[47.17634633400013,9.484981323000085],[47.159809876000054,9.492629435000083],[47.145392151000124,9.503481486000112],[47.12937245700007,9.511853068000107],[47.108030091000074,9.512369832000047],[47.09469757200014,9.50286136800014],[47.083948874000036,9.487565145000104],[47.073226014000106,9.475886271000121],[47.063898417000075,9.477023153000118],[47.05935089100004,9.499554077000141],[47.052400412000054,9.560635620000141],[47.05687042300007,9.58120284000003]]]},"properties":{"name":"Liechtenstein","iso_a2":"LI"},"links":[{"href":"http://my-base-server.ch:7080/rest/services/myservice/collections/countries/items/156?f=json","rel":"self","type":"application/geo+json","title":"This document"},{"href":"http://my-base-server.ch:7080/rest/services/myservice/collections/countries/items/156?f=html","rel":"alternate","type":"text/html","title":"This document as HTML"},{"href":"http://my-base-server.ch:7080/rest/services/myservice/collections/countries?f=json","rel":"collection","type":"application/json","title":"The collection the feature belongs to"}]}
```

and the corresponding WKT from the PostGIS database:
```
"POLYGON((9.58120284000003 47.05687042300007,9.560635620000141 47.052400412000054,9.499554077000141 47.05935089100004,9.477023153000118 47.063898417000075,9.475886271000121 47.073226014000106,9.487565145000104 47.083948874000036,9.50286136800014 47.09469757200014,9.512369832000047 47.108030091000074,9.511853068000107 47.12937245700007,9.503481486000112 47.145392151000124,9.492629435000083 47.159809876000054,9.484981323000085 47.17634633400013,9.487358439000047 47.210013529000065,9.504618368000138 47.243732402000035,9.52115482500011 47.262801005000114,9.530249878000092 47.25365427700004,9.547096395000068 47.243034770000065,9.540378458000134 47.229107972000065,9.544822632000148 47.22032297800007,9.554331095000123 47.21161549900012,9.562909383000061 47.19774037700006,9.561875854000078 47.190609029000115,9.551953979000103 47.17557118800001,9.552057332000118 47.16688954700007,9.5818229570001 47.15490061500009,9.605594116000077 47.13226633700006,9.615722697000109 47.10676401800003,9.608798055000136 47.08077077300007,9.58120284000003 47.05687042300007))"
```

More:

PostgreSQL version: 13.3

PostGIS version: 3.1 (USE_GEOS=1 USE_PROJ=1 USE_STATS=1)

May this https://postgis.net/2013/08/18/tip_lon_lat/ be the source of the problem? Or did I miss something in the config of the provider/service yaml files?

**Comment by azahnen** [comment]
This looks like an issue with the `nativeCrs` in the provider. If it is not set, try to add this to the yaml file:
```
nativeCrs:
  code: 4326
```

**Comment by swiss-knight** [comment]
It seems to be actually set up at the very top of the provider yaml file:
```
cat ./store/entities/providers/service.yml 
---sh
id: service
createdAt: 1643145562759
lastModified: 1643145562759
entityStorageVersion: 2
providerType: FEATURE
featureProviderType: SQL
nativeCrs:
  code: 4326
  forceAxisOrder: NONE
(...)
```

May this be related to the `forceAxisOrder` element?

**Comment by cportele** [comment]
If `forceAxisOrder` is `NONE`, it will use the axis order of the coordinate reference system, which is latitude/longitude for epsg:4326. From the WKT example, the geometries in the database are in longitude/latitude, so this should be:

```yaml
nativeCrs:
  code: 4326
  forceAxisOrder: LON_LAT
```

**Comment by swiss-knight** [comment]
Indeed, I just went [there](https://github.com/interactive-instruments/ldproxy/tree/master/docs/de/configuration/providers) and also figured it out! Thanks.
<br>

Per PostGIS [documentation](https://postgis.net/2013/08/18/tip_lon_lat/):
> In mapping frameworks spatial coordinates are often in order of latitude and longitude.    
> In spatial databases spatial coordinates are in x = longitude, and y = latitude.

And the order of WGS84 coordinates is (latitude, longitude) as per: https://epsg.org/crs_4326/WGS-84.html

So maybe when reading WKT geometries from PostGIS it could be interesting to set `forceAxisOrder` default to `LON_LAT` then. Just a thought. ;-)
