### ISSUE TITLE
support nested indexes

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#61]
We support indexes on properties. When an index is enabled for a property, ldproxy will get and cache a distinct list of values of the property. That list can be accessed in the html view to browse filtered views of the feature collection.

The goal of this enhancement would be to support nested indexes. So when browsing a first level value, e.g. from country, a second list with cities in that country would be presented.

**Comment by cportele** [comment]
The experimental capability has been removed from the code for some time.
