### ISSUE TITLE
Server error when accessing some of the collections in data

### ISSUE THREAD

**Issue by codehub-rony** [interactive-instruments/ldproxy#613]
Hi,

I'm getting a server error when trying to view data inside a collection. I have a sql connection to a local database. I connected it using `host.docker.internal` as a host. 

I'm running default docker image with `docker run -d -p 7080:7080 -v ldproxy_data:/ldproxy/data iide/ldproxy:latest` as mentioned in the docs. 

I can see all the collections via http://localhost:7080/rest/services/bag-geotoko/collections. Some of these work fine, no issues. But others give an internal server error when clicking on the collection. Log shows this error: `Server Error with ID c45e869ebff0a3c1: IO operation was stopped unexpectedly after 0 bytes because of java.lang.ArrayIndexOutOfBoundsException: Index 50 out of bounds for length 50`

Any idea what is going wrong? Is there something wrong in the data? 

The data I'm using is [a small postgis dump](https://geocatalogus.nl/dataset/bag-extract-database-dumps/resource/5a003cd9-68a8-4a1f-8aeb-885097cf07fb)

I imported it to the db using the pg_restore as mentioned in the link `pg_restore -Fc -d bag -h localhost -p 5432 -U postgres -W bag-voorbeeld.dump`.

There are quite some tables in there, but to scope things down: `gemeente` table is an example of a collection that is working fine. `pand` is giving the error.

**Comment by azahnen** [comment]
Hi, could you enable some log options in `cfg.yml` and post the log?

```
logging:
  sqlQueries: ON
  stackTraces: ON
```

**Comment by codehub-rony** [comment]
I enabled the extra logging.

xtraplatform.log:

```
DEBUG [2022-02-25 10:55:00,658] localdb                  - Executing statement: WITH
    NR AS (SELECT MIN(SKEY) AS minKey, MAX(SKEY) AS maxKey, count(*) AS numberReturned FROM (SELECT A.gid AS SKEY FROM pand A ORDER BY SKEY LIMIT 10) AS IDS),
    NM AS (SELECT count(*) AS numberMatched FROM (SELECT A.gid AS SKEY FROM pand A ORDER BY 1) AS IDS) 
  SELECT * FROM NR, NM  
DEBUG [2022-02-25 10:55:00,670]                          - Execution of prepared statement took 1ms  
DEBUG [2022-02-25 10:55:00,671] localdb                  - Executing statement: SELECT A.gid AS SKEY, A.gid, A.identificatie, A.aanduidingrecordinactief, A.aanduidingrecordcorrectie, A.officieel, A.inonderzoek, A.begindatumtijdvakgeldigheid::timestamp(0), A.einddatumtijdvakgeldigheid::timestamp(0), A.documentnummer, A.documentdatum::timestamp(0), A.pandstatus, A.bouwjaar, A.geom_valid, ST_AsText(ST_ForcePolygonCCW(A.geovlak)) FROM pand A WHERE (A.gid >= 1 AND A.gid <= 10) ORDER BY 1  
DEBUG [2022-02-25 10:55:00,678]                          - Execution of prepared statement took 4ms  
ERROR [2022-02-25 10:55:00,685] localdb                  - Server Error with ID 2757344c25cccf1d: IO operation was stopped unexpectedly after 0 bytes because of java.lang.ArrayIndexOutOfBoundsException: Index 50 out of bounds for length 50   
```

requests.log:
```
172.17.0.1 - - [25/Feb/2022:11:57:48 +0100] "GET /rest/services/localdb/collections/pand/items HTTP/1.1" 500 759 "http://localhost:7080/rest/services/localdb/collections" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 43
172.17.0.1 - - [25/Feb/2022:11:57:48 +0100] "GET /ogcapi-html/assets/style-common.c9007587.css HTTP/1.1" 304 0 "http://localhost:7080/rest/services/localdb/collections/pand/items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 5
172.17.0.1 - - [25/Feb/2022:11:57:48 +0100] "GET /ogcapi-html/assets/common.a4137ee2.css HTTP/1.1" 304 0 "http://localhost:7080/rest/services/localdb/collections/pand/items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 5
172.17.0.1 - - [25/Feb/2022:11:57:48 +0100] "GET /ogcapi-html/assets/favicon.ccbcb955.ico HTTP/1.1" 304 0 "http://localhost:7080/rest/services/localdb/collections/pand/items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 2
```

**Comment by codehub-rony** [comment]
I found an issue with the data which sort of fixed the problem. But not entirely.

I found out that the collections giving a `500` http status all have a Z dimension in the geometry. I created new tables using and transfomred these to 2D geoms.
```
CREATE TABLE bagactueel.multi_pand AS SELECT gid, ST_Multi(ST_Force2D(geovlak)) as geovlak from bagactueel.pand;
ALTER TABLE bagactueel.multi_pand ADD PRIMARY KEY (gid);
```

The pages now work. However, the extent of the selected collection and the geometries of individual items are not shown on the maps.

**Comment by azahnen** [comment]
Mixed 2d and 3d geometries are currently not supported. Since the given nativeCrs is 2d, the approach with st_force2d looks like the right way. 
I guess either copying the table does not create the needed postgis metadata or there is an error in your provider configuration. If you need more help I would need the queries log again and the section from the provider configuration for the given table.

**Comment by cportele** [comment]
I have created #614 as a follow-up. Thanks.
