### ISSUE TITLE
Paging error in HTML-mode (f=html) when using a filter with a numeric character string

### ISSUE THREAD

**Issue by Sverre-Iversen** [interactive-instruments/ldproxy#634]
**The encoded URL query string is somehow corrupted after HTML-paging.**

**Example 1: String with two numeric characters ("15"):**
Before paging: filter=fylkesnummer like '%15%' _--encoded-->_ filter=fylkesnummer+like+%27%2515%25%27
After paging: filter=fylkesnummer+like+%27%15%25%27 _--decoded-->_ filter=fylkesnummer+like+'%' (**which is wrong**)

**Example 2: String with four numeric characters ("4203"):**
Before paging: filter=kommunenummer like '%4203%' _--encoded-->_ filter=kommunenummer%20like%20%27%254203%25%27
After paging: filter=kommunenummer+like+%27B03%25%27 _--decoded-->_ filter=kommunenummer+like+'B03%' (**which is wrong**)

**Example 3: String with a non-numeric character (","):**
Before paging: filter=fylkesnummer+like+'%,%' _--encoded-->_ filter=fylkesnummer+like+%27%25%2C%25%27
After paging: filter=fylkesnummer+like+%27%25%2C%25%27 _--decoded-->_ filter=fylkesnummer+like+'%,%' (**<ins>which is correct</ins>**)

**This is NOT an issue for JSON-paging (f=json)**

**Comment by azahnen** [comment]
Thanks for the catch!

It can be reproduced with the demo deployment when using paging here: https://demo.ldproxy.net/strassen/collections/abschnitteaeste/items?filter=kennung+like+%27%2512015%25%27
