### ISSUE TITLE
Unable to disable the manager

### ISSUE THREAD

**Issue by maaattes** [interactive-instruments/ldproxy#652]
I'm unable to disable the manager. According to the [documentation](https://github.com/interactive-instruments/ldproxy/blob/master/docs/de/configuration/global-configuration.md#manager) this should be possible by setting

```yaml
manager:
  enabled: false
```

in `cfg.yml`. But this setting seems to have no effect  😕
I'm using v3.2.2 and tried it with my remote deployment as well as with a local docker container.

**Comment by azahnen** [comment]
Confirmed, thanks for the catch. The bug was introduced in v3.2.0.

**Comment by azahnen** [comment]
Fixed in v3.2.3.
