### ISSUE TITLE
issues and improvement suggestions for docs.ldproxy.net

### ISSUE THREAD

**Issue by rkoblenzer** [interactive-instruments/ldproxy#665]
Issues:
* [x] Probably missing headings, examples: 
  * https://docs.ldproxy.net/de/#vorraussetzungen
  * Bausteine -> Vector Tiles leads to https://docs.ldproxy.net/de/services/building-blocks/tiles.html#umfang (but there is some text before "Umfang" which I unterstand as "Allgemein" / "Common").
* [x] Broken link: https://docs.ldproxy.net/de/services/building-blocks/tiles.html#optionen (all links in the deprecated options to the Tile Provider, example: tileEncodings: https://docs.ldproxy.net/de/services/building-blocks/tiles.html#tile-provider-features) 
* [x] Incorrect link: https://docs.ldproxy.net/de/services/building-blocks/features_-_html.html: The [link](https://docs.ldproxy.net/services/building-blocks/#transformations) to "transformations" in option "transformations".
* [x] Broken links in https://docs.ldproxy.net/de/application/40-store.html (configuration-object-types, special-cases), DE & EN

Ideas and improvement suggestions:
* [x] An overall search or at least a link to Google search with "site:..." would be useful.
* [x] Consistent entry points for every heading ("Common" / "Allgemein"), not only in some chapters. Or even better: clickable headings, so the first page does not need to be "Common". Since the headings are in bold, at first, I was a little bit confused that I they were not links.
* [x] Avoid "Auf dieser Seite" / "On this page" without any entries underneath, Example: https://docs.ldproxy.net/de/#vorraussetzungen
* [x] The heading "Fortgeschritten" / "Advanced" is confusing because it is just the heading without any body (at least it could contain a notice that the content is in preparation)

**Comment by azahnen** [comment]
Closing, all issues were fixed in the meantime.
