### ISSUE TITLE
timeZone for logging has no effect

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#685]
### ldproxy Version

3.2.4

### Current Behavior

Setting the timeZone in the global configuration cfg.yml in logging/appenders/timeZone has no effect. The log is using UTC.  

In addition, logging/appenders/logFormat is created by default, but ignored.

### Expected Behavior

* Only auto-create entries in cfg.yml that can be used to control the log output.
* Clarify how to set the timezone in the log files.

### Steps to Reproduce

Use any deployment with an auto-generated cfg.yml and try to change the timezone.

**Comment by azahnen** [comment]
The auto-generated cfg.yml has to be from an earlier version, from v3.2.0 on it is not generated anymore.
The issue itself is fixed in the current build.
