### ISSUE TITLE
tooltip labels for start/stop button are backwards

### ISSUE THREAD

**Issue by rockliffelewis** [interactive-instruments/ldproxy#686]
### ldproxy Version

latest

### Current Behavior

When a service is started if you hover over the start button the tooltip says 'start service'
When a service is stopped, the tooltip says 'stop service'

### Expected Behavior

It would make more sense the other way around, the tooltip should tell you what clicking the button is going to do

### Steps to Reproduce

Hover your cursor over the service start stop button in the management console

**Comment by azahnen** [comment]
Thanks for the catch, confirmed for English only.

**Comment by azahnen** [comment]
The issue is fixed in `iide/ldproxy:next`.
