### ISSUE TITLE
Support 3D Tiles

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#692]
Support [3D Tiles](https://github.com/CesiumGS/3d-tiles) for 3D building datasets and eventually the emerging [OGC API GeoVolumes](https://ogcapi.ogc.org/geovolumes/) standard.

This change will support visualization of CityGML-based building models.

Build on #545 and add support for 3D Tiles using the extensions of [3D Tiles Next aka 3D Tiles 1.1](https://github.com/CesiumGS/3d-tiles/tree/draft-1.1#version-history), in particular:

* [Directly support glTF assets as tile contents](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_content_gltf)
* [Support for implicit quadtree tiling schemes](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_implicit_tiling)

The feature provider must meet the requirements of the "Features glTF" building block.

~~The best approach would be to include this in the TILES resources.~~ (This is probably not a good idea, because Tiles and GeoVolumes have very different maturity levels as standards. Capabilities used by both 2D and 3D Tiles could be moved to xtraplatform-spatial instead.)

Open issues which could be moved to new/existing issues:

* Upgrade to the new cache logic used by TILES.
* Seeding: The current logic requires a synchronization between the different threads (all threads except the first have to wait until the root subtree has been created). Right now this uses a waiting pattern. Is there a better way to synchronize between task contexts?
* The current [OGC API GeoVolumes](https://ogcapi.ogc.org/geovolumes/) draft has open issues and in particular does not use the media type specified by the 3D Tiles specification. There are a number of TODOs in the code that reference these issues.

**Comment by azahnen** [comment]
Regarding task synchronization: I don't think there is a better mechanism yet, the current design assumes that partial tasks are independent. 
I already thought about a better design using a job queue which would be a prerequisite for distributed seeding.  I will take into account dependent sub-tasks when drafting a rough concept for that.
