### ISSUE TITLE
Exceptions are not routed via the ldproxy exception handler

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#697]
### ldproxy Version

master

### Current Behavior

All (?) exceptions are no longer routed to the ldproxy exception handler and result in a direct 500 response. This is also problematic in development as no information about any exceptions is logged (no messages and no stacktraces), just the information about the 500 response.

### Expected Behavior

Exceptions are routed to the ldproxy exception handler.

### Steps to Reproduce

Start ldproxy using `iide/ldproxy:next` with any API configuration. Use GET on some API URI that is not a resource. The response is a 500. With `iide/ldproxy:latest` the response is a correct 404.

### Relevant log output

```shell
n/a
```

**Comment by azahnen** [comment]
Confirmed. The exceptions are routed to the ExceptionMapper, but an NPE is thrown for every exception that does not have a cause. The bug was introduced in #676.
