### ISSUE TITLE
add access control for GET operations

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#718]
This introduces the option to restrict access to `GET` operations in addition to writing operations. It also introduces the roles `read` and `write` which users need to have to access the corresponding operations.

The `secured` option for APIs is deprecated and replaced by `accessControl`, which has two child options.
- The `mode` option defines if access control is disabled (`OFF`), enabled but only for a subset of operations (`RESTRICTED`) or enabled for all operations (`PRIVATE`). 
- The `public` option defines public roles/permissions that every authenticated and non-authenticated user owns when the `mode` is `RESTRICTED`, so it defines the public part of the API. 

These are the default settings:

```yaml
accessControl:
  mode: RESTRICTED
  public:
  - read
```

The behavior with the default settings is close to the previous default `secured: true`, with the addition that not every authenticated user may access writing operations, but only users with role `write`.

**Comment by cportele** [comment]
Just for clarity: The rules for `GET` will also apply to `HEAD`.

We also need to look at `OPTIONS`.
