### ISSUE TITLE
need better documentation of JSON-LD and microdata configuration

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#75]
maybe also improve support in the Manager UI

**Comment by cportele** [comment]
the module has been removed

**Comment by akuckartz** [comment]
?!

**Comment by cportele** [comment]
Other software changes would have required a rewrite of the module, but since there was no interest (that we were aware of) in the old JSON-LD module, this has not happened and the module will not be part of the next release. 

That said, instead of a separate JSON-LD output there will be an experimental capability to extend the GeoJSON output with JSON-LD annotations. We will add documentation about this in the coming weeks.
