### ISSUE TITLE
Update www.ldproxy.net

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#83]
www.ldproxy.net needs an update: 
* It still uses an old release version and needs to be updated to the latest 1.2.x release.
* That deployment sometimes goes into a mode that only returns proxy errors, but it is not clear from the logs why this happens. We do not see this behaviour in other deployments, so we suspect that this is an issue related to the particular versions of ubuntu and docker, so hopefully an update will fix this issue, too.
* We should add additional services includes some INSPIRE WFS.

**Comment by ubergesundheit** [comment]
Please also consider adding CORS headers to enable websites to consume the data of the instance.
cc https://github.com/giatschool/webgis.nrw/issues/30

**Comment by ubergesundheit** [comment]
Does this mean the instance www.ldproxy.net is dead?

**Comment by cportele** [comment]
For some time we have not maintained www.ldproxy.net. The services at ldproxy.nrw.de will continue to be maintained (and be updated soon).
