### ISSUE TITLE
tiles follow-up

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#845]
- [x] ~TileMatrixSets should be entities, not resources~ moved to #877
- [x] publish metadata like zoomLevels + center in `TileProvider`, use in API (see `TilesDataHydrator.process`)
- [x] ~~integrate `ogcapi-maps` into `ogcapi-tiles`~~ delete `ogcapi-maps`

**Comment by azahnen** [comment]
@cportele Regarding `layers`, I think the alternative we already discussed before would be `tilesets`. That is also what the MBTiles Spec mostly uses in regard to an MBTiles file.

> One MBTiles file represents a single tileset, optionally including grids of interactivity data. Multiple tilesets (layers, or maps in other terms) can be represented by multiple MBTiles files.

**Comment by cportele** [comment]
@azahnen - Yes, that works! It is also directly reflects the FEATURES case where each collection has a tileset (per tile matrix set) and a dataset tileset combining the collection tilesets.
