### ISSUE TITLE
support WFS with HTTP basic auth

### ISSUE THREAD

**Issue by ubergesundheit** [interactive-instruments/ldproxy#86]
Is it possible to consume web feature services with simple http authentication?

I managed to add a service which is protected by simple http authentication by adding the url like this:
http://user:password@normalurl

It would be beneficial if it would be possible to specify username and password through the web interface

**Comment by ubergesundheit** [comment]
Addition:
Adding and listing of featureclasses is working, but viewing the service does not. I am getting this error:
```

**Comment by azahnen** [comment]
As you found out this is not properly supported, but this is definitely an important feature that we will put on the roadmap.

**Comment by azahnen** [comment]
This is supported in the latest version.
