### ISSUE TITLE
API does not start, but no error message

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#866]
### ldproxy Version

3.3.1

### Current Behavior

If a services configuration includes the configuration of an unknown building block, the services is not started, but no error is logged and no information that the service is not started. Previously, the fact that an error has been detected was logged including the fact that the service could not be started.

### Expected Behavior

Add error messages to the log for any issues while starting an API.

### Steps to Reproduce

Add an unknown building block, e.g., `- buildingBlock: FOOBAR` to the service configuration and start ldproxy.

**Comment by azahnen** [comment]
I cannot confirm the issue. When adding an unknown building block, the service does not start and an error message is logged:

```
Cannot load 'entities/services/krankenhaus.yml': Could not resolve type id 'FOOBAR'
```

If it behaves differently for you, please provide a more detailed example.

**Comment by cportele** [comment]
Hm, good question, I also now always get that message. I guess it was there, too, but that I missed it because the error is written early and there are lots of codelists that are loaded/logged after the error.

However, I remember that previously there was a final error message "Service with id 'xyz' could not be started." when a service could not be started and that is no longer there. Or was that never logged for these errors?

**Comment by azahnen** [comment]
I don't think so, since it is a deserialization error, ldproxy does not even try to start the service. To change that, we would have to register some kind of catch-all unknown building block which would allow us to handle the error in a higher layer.

**Comment by cportele** [comment]
OK, I am closing the issue.
