### ISSUE TITLE
Proxying ld-proxy (mostly works, but...)

### ISSUE THREAD

**Issue by KathiSchleidt** [interactive-instruments/ldproxy#93]
Hiya,
I wanted to proxy ld-proxy to get rid of the 7080 port (problem getting past administrative firewalls).
Ideally, it wouldn't conflict with the other apps I've got on my apache, so assigned it to its own subdirectory, apache config as follows:
```
ProxyPass /ldproxy/ http://localhost:7080/
ProxyPassReverse /ldproxy/ http://localhost:7080/
```
While this mostly works, it runs into problems, not possible to configure a new data source (and the old ones are no longer visible). It seems to depend on the URI path being called to determine where to store its files; adding an ldproxy directory got me further (but still not where I wanted to be :( ), copying the config files from the docker directory also didn't help.

I've now configured it to proxy /manager/ and /rest/ on to ld-proxy - are there any other sub-uris that must be taken into account?
:)
Kathi

**Comment by azahnen** [comment]
Hi Kathi, actually there is an undocumented (sorry!) configuration parameter for your use case, but it does not work when adding a subfolder like you do. So this is a bug I will look into #94.

Until then you could create a `VirtualHost` with a subdomain `ldproxy`, then add a `ProxyPass` for the root folder of that subdomain and set the `externalURL` setting in ldproxy.
For that you would have to open the file `xtraplatform.json` in your docker volume and add the key `externalURL` with you URL at the top, e.g.:
```
{
    "externalURL": "http://ldproxy.your-hostname-or-domain/",
    "useFormattedJsonOutput": true,
    "allowServiceReAdding": false,
    ...
}
```
Hope this helps
Andreas

**Comment by cportele** [comment]
See #94.
