### ISSUE TITLE
feature "id" property case sensitivity

### ISSUE THREAD

**Issue by pduchesne** [interactive-instruments/ldproxy#95]
The json encoding of features uses an uppercase "ID" property (at least in the https://www.ldproxy.nrw.de service)
This is wrong as per the geojson spec; it must be lowercase.

**Comment by cportele** [comment]
Thanks, Phillipe! That is a configuration error for some feature types of the cadastral data. For the topographic data it seems to be correct for the feature types that I have checked ([example](https://www.ldproxy.nrw.de/topographie/AX_Bahnverkehrsanlage/DENWAT01D000AbNu/?f=json)).

@azahnen, @boehmesven: I have updated the local configuration for the ldproxy.nrw.de services.

**Comment by azahnen** [comment]
I checked the implementation, the default is "id", so I am closing this.
