### ISSUE TITLE
links in response body

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#97]
The spec defines various links that should be added to the collection metadata, the collections and the features. We should implement all of them.

**Comment by azahnen** [comment]
Links in JSON bodies are implemented. I will check other mime types.

**Comment by cportele** [comment]
Reported by @tschaub: 

It looks like links are being generated differently depending on accept header or f query param
e.g. `curl 'http://wfs3hackathon.ldproxy.net/rest/services/de_gn/?f=json'` generates collection links like http://wfs3hackathon.ldproxy.net/rest/services/de_gn/namedplace?f=json (which looks right) and `curl 'http://wfs3hackathon.ldproxy.net/rest/services/de_gn/' --header 'accept: application/json'` generates collection links without the collection name/id http://wfs3hackathon.ldproxy.net/rest/services/de_gn/ (which looks wrong).

**Comment by cportele** [comment]
Reported by @rouault:

"http://wfs3hackathon.ldproxy.net/rest/services/de_gn/namedplace?count=10&name.spelling.text=Sandharlanden" has a next link to "http://wfs3hackathon.ldproxy.net/rest/services/de_gn/namedplace?name.spelling.text=Sandharlanden&page=2&count=10", but this next page is empty and also references page=3 etc.

**Comment by azahnen** [comment]
@cportele The first issue should be fixed. 
The paging does not take numberReturned into account yet. I will not fix this now, I have to merge the new paging code with the existing html paging.

**Comment by azahnen** [comment]
Previous and next links work correctly now. Links for XML/GML bodies were implemented as well.
